### ISSUE TITLE
The OperatorHub display names for Driver in not consistent with the product names

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#1]
Taken from https://github.com/IBM/ibm-spectrum-scale-csi-operator/pull/111

The product name should be "IBM Spectrum Scale CSI" and we have places in the code that mention "IBM CSI Spectrum Scale", this should be made consistent on all the files in the code base.

**Comment by Jainbrt** [comment]
@mew2057 if fixed, can we closed this ?
