### ISSUE TITLE
operator upgrade does not  delete old deployment in error case.

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#107]
**Describe the bug**
upgrade on 02/22 was failing due to incorrect images  #103,  i ran ` oc apply -f ibm-spectrum-scale-csi-operator.yaml` multiple times.
It does not delete deployment/statefulset

```
oc get all  -n ibm-spectrum-scale-csi-driver
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/ibm-spectrum-scale-csi-operator-5f5f549754-bvnbl   2/2     Running   0          3d1h

NAME                                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/ibm-spectrum-scale-csi-operator-metrics   ClusterIP   172.20.220.111   <none>        8686/TCP,8383/TCP   3d2h

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ibm-spectrum-scale-csi-operator   1/1     1            1           4d4h

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/ibm-spectrum-scale-csi-operator-5c64899cc7   0         0         0       3d2h
replicaset.apps/ibm-spectrum-scale-csi-operator-5f5f549754   1         1         1       3d1h
replicaset.apps/ibm-spectrum-scale-csi-operator-6d5dbbcff7   0         0         0       3d2h
replicaset.apps/ibm-spectrum-scale-csi-operator-7dffcf977c   0         0         0       4d4h
[root@c943f6n01-pvt v1.0.1]#
```
**To Reproduce**
1. upgrade operator using CLI method .. ensure that upgrade of operator image  fails due to incorrect image
2. upgrade with fixed  problem of operator image but CSI driver should be incorrect
3. fix both above issue and upgrade operator

**Expected behavior**

**Environment**
Please run the following an paste your output here:
``` bash
# Developement
operator-sdk version 
go version

# Deployment
kubectl version
rpm -qa | grep gpfs
```
**Screenshots**

**Additional context**

**Comment by mew2057** [comment]
This _should_ be handled by the  `CSI_DRIVER_IMAGE` environment variable in the deployment that you apply with the upgrade. The immediate workaround is to set the  `spectrumScale` field in the  CR to `quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v1.1.0`. This is  assuming that the issue is related to the `CSI_DRIVER_IMAGE` not  working.

Can you give me the output of:
```
get deployment -n ibm-spectrum-scale-csi-driver ibm-spectrum-scale-csi-operator -o yaml | grep -c CSI_DRIVER_IMAGE
```

You should get back either a  2 or 3 (depending on history).

---
Additionally, can I get the status  on the `DaemonSet` or output from one of the  failing pods in the `DaemonSet`?

**Comment by mew2057** [comment]
Looking at my environment, it looks like the Environment variable change  does  not work.

```
[root ~]# kubectl describe pods -n ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-xzkz7 | grep image
  Normal  Pulled     3m7s       kubelet, jdun-worker1  Container image "quay.io/k8scsi/csi-node-driver-registrar:v1.0.1" already present on machine
  Normal  Pulled     3m6s       kubelet, jdun-worker1  Container image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v1.0.0" already present on machine
```

For now this is out of  scope for the 1.1.0 timeframe as it will require a more detailed examination of the  environment setting. The  `SpectrumScale` field in the Custom Resource can be used as intended for this release.

**Comment by gandhisanjayv** [comment]
```
oc get deployment -n ibm-spectrum-scale-csi-driver ibm-spectrum-scale-csi-operator -o yaml | grep -c CSI_DRIVER_IMAGE
3
```

**Comment by mew2057** [comment]
Just realized  that I was overriding the `spectrumScale` in my CR.

**Comment by mew2057** [comment]
I removed the `spectrumScale` from my CR and this is  what I get now:

```
kubectl describe pods -n ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-rdjlr  | grep Image:
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
    Image:         quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v1.1.0
```

**Comment by mew2057** [comment]
I'll need the output of:

```
kubectl get DaemonSets -n ibm-spectrum-scale-csi-driver ibm-spectrum-scale-csi -o yaml | grep image

```

In my environment it looks  like this:
```
        image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
        imagePullPolicy: IfNotPresent
        image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v1.1.0
        imagePullPolicy: IfNotPresent
```

**Comment by gandhisanjayv** [comment]
i was in process of deleting CSI driver .. i deleted CR

**Comment by gandhisanjayv** [comment]
created CR again
```
 oc get DaemonSets -n ibm-spectrum-scale-csi-driver ibm-spectrum-scale-csi -o yaml | grep image
        image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
        imagePullPolicy: IfNotPresent
        image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v1.1.0
        imagePullPolicy: IfNotPresent
```

**Comment by mew2057** [comment]
1. When you delete, what  is the status of the  `DaemonSets`, and `StatefulSets`.

2. What does the  operator log look like? 
They  should all be moved to deleting, but if something bad is happening in the driver  code on tear-down we could see this occur.

3. Is the CR still present when you  have  the state in the top level issue?

**Comment by gandhisanjayv** [comment]
[ibm-spectrum-scale-csi-operator-5f5f549754-bvnbl-ansible.log](https://github.com/IBM/ibm-spectrum-scale-csi/files/4247401/ibm-spectrum-scale-csi-operator-5f5f549754-bvnbl-ansible.log)
[ibm-spectrum-scale-csi-operator-5f5f549754-bvnbl-operator-previous.log](https://github.com/IBM/ibm-spectrum-scale-csi/files/4247402/ibm-spectrum-scale-csi-operator-5f5f549754-bvnbl-operator-previous.log)

**Comment by gandhisanjayv** [comment]
When you delete, what is the status of the DaemonSets, and StatefulSets : **Healthy**

    Is the CR still present when you have the state in the top level issue?  **"yes"**

**Comment by gandhisanjayv** [comment]
operator should save logs before it starts upgrade .

**Comment by mew2057** [comment]
```
When you delete, what is the status of the DaemonSets, and StatefulSets : **Healthy**

Is the CR still present when you have the state in the top level issue?  **yes**
```
This means that the  delete didn't finish yet, you're still in  the `finalizer` and removing one of the driver components is getting stuck. 

The clear  evidence is in `ibm-spectrum-scale-csi-operator-5f5f549754-bvnbl-ansible.log`. The `remove` run has  not completed, so you can't see the output in the  `ansible` container. The `operator`  container should be able to show you the hanging point.

```
kubectl logs -n ibm-spectrum-scale-csi-driver <YOUR OPERATOR CONTAINER> operator
```

@ yesterday's comment: I'm not really sure that there  is  a mechanism that would allow that to work. Unless we set up a sidecar  or endpoint  to stash the logs, there isn't really  a mechanism for saving logs. There are sidecar solutions for this I believe,  but it's going to require research, and be a low priority.

**Comment by smitaraut** [comment]
@mew2057 is the CSI_DRIVER_IMAGE environment variable support there in v1.1.0? If yes, can you add a comment on how to use it in [https://rtpdoc01.rtp.raleigh.ibm.com:9443/kc/STXKQY_5.0.4_review/com.ibm.spectrum.scale.csi.v5r04.doc/bl1_csi_scaleoperator_config.html](InfoCenter)-

**Comment by mew2057** [comment]
It is supported, but I'm not sure if I want to full expose the interface as a supported path.  I think that if a user needs to modify their deployment the CR is still the correct mechanism. The `CSI_DRIVER_IMAGE` is  just a utility to bake image configs  that can be  consumed by testers. 

@dunnevan any thoughts  on  this?

**Comment by dunnevan** [comment]
I agree that we shouldn't expose the ENV variables to users.  The reason is: ENV variables have to be baked into the operator image, or have to be passed into the operator deployment, which conflicts with our recommendation of using operatorhub and subscriptions.

Generally, I don't expect anyone to want to override the sidecars either.  There really is not a legit reason for it, nor do we support sidecar deployments outside of what we have tested.
