### ISSUE TITLE
TravisCI is failing with `{'lint': ['must be of string type']}` 

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#109]
The Travis tests run in the PR are failing with `{'lint': ['must be of string type']}` 

Doing some searching, it looks like this is probably caused by molecule being >= 3 and we're using a yaml file that is < 3...  

https://molecule.readthedocs.io/en/latest/configuration.html#lint

**Comment by mew2057** [comment]
Closing, because this has been resolved.
