### ISSUE TITLE
application pod remains in terminating if kubelet root directory is a softlink

### ISSUE THREAD

**Issue by deeghuge** [IBM/ibm-spectrum-scale-csi#1102]
## Describe the bug
in case kubelet root directory(/var/lib/kubelet) is softlink from some other filesystem then pod using csi pvc remains in pod terminating state

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

create softlink from /mnt/kubelet to /var/lib/kubelet and try deleting the pod 

### Data Collection and Debugging

Environmental output

- What openshift/kubernetes version are you running, and the architecture? 
- `kubectl get pods -o wide -n < csi driver namespace> `
- `kubectl get nodes -o wide`
- IBM Storage Scale container native version 
- IBM Storage Scale version 
- Output for `./tools/storage-scale-driver-snap.sh -n < csi driver namespace> -v `

Tool to collect the CSI snap:

`./tools/storage-scale-driver-snap.sh -n < csi driver namespace>`

### Add labels

- Component:
- Severity:
- Customer Impact:
- Customer Probability:
- Phase:

Note : See [labels](https://github.com/IBM/ibm-spectrum-scale-csi/labels) for the labels

**Comment by saurabhwani5** [comment]
I have verified the fix #1117 , thank @badri-pathak
