### ISSUE TITLE
Scale GUI not returning list of remote filesystems

### ISSUE THREAD

**Issue by scolbeck** [IBM/ibm-spectrum-scale-csi#1119]
Remote mount Scale via Fusion SDS 2.7.1.

All CP4D PVCs remain in the `Pending` state due to `ProvisioningFailed`.  Preliminary investigation shows a connection problem with the remote Scale mounts and the Scale GUI call not returning the list of remote filesystems.
```
url -X GET -u 'CsiAdmin:EpOYRdXZy87-BsqRCtw7' -k https://ibm-spectrum-scale-gui-ibm-spectrum-scale.apps.sre-bar-3m17w-fips-ss-781.cp.fyre.ibm.com:443/scalemgmt/v2/filesystems/remote/filesets
{
  "filesets" : [ ],
  "status" : {
    "code" : 200,
    "message" : "The request finished successfully."
  }
}
```

See related issues for more information.  The Fusion issue has the most details regarding the Scale problem:
 - CP4D issue: https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/17028
 - Fusion issue: https://github.ibm.com/ProjectAbell/abell-tracking/issues/33101

**Comment by deeghuge** [comment]
Opened issue in scale-core repo for gui team
