### ISSUE TITLE
Support for mutiple snapshot creation/deletion per CG

### ISSUE THREAD

**Issue by hemalathagajendran** [IBM/ibm-spectrum-scale-csi#1136]
Support for creating multiple snapshots (atleast 1k snapshots) in parallel by increasing worker threads to 10.
Support for creation/deletion per CG in parallel.

**Comment by hemalathagajendran** [comment]
https://github.com/IBM/ibm-spectrum-scale-csi/pull/1123

**Comment by deeghuge** [comment]
@hemalathagajendran do track the RW stories from RTC or scale-core github
