### ISSUE TITLE
Documentation improvements for 1.1.0

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#114]
- [x] There is an operatorhub link.  The operatorhub link does not link to the KC

- [x] Both github and operatorhub link to readthedocs, which is not our formal documentation.  (this may be ok for in-dev code, but is this what we want for GA'd code - legal has not yet approved readthedocs)

- [x] operatorhub links to an operator readme in the old operator github repo (a remanent of us leaving the operator at 1.0.0)

- [x] We are lacking support statements in our github.  In other words, we need to be clear that our GA'd offering is considered part of the Spectrum Scale product and is supported via those processes.    Whereas, our github is supported on a best effort basis.

**Comment by mew2057** [comment]
Added a link to KC at the top of the  main section. Added more general doc call out in  OperatorHub to the github repository.

**Comment by deeghuge** [comment]
Closing this issue as documentation fixes for release v1.1.0 are already merged.
