### ISSUE TITLE
Feature to support password rotation in the CSI operator and driver

### ISSUE THREAD

**Issue by badri-pathak** [IBM/ibm-spectrum-scale-csi#1148]
**Is your feature request related to a problem? Please describe.**
In the current functional availability, when the credentials gets changed, then every-time resources automatically recreates/restarts, leading to wait for 5minutes. 

**Describe the solution you'd like**
Feature to support password rotation without resources restart/recreate in the CSI operator and driver.

**Describe alternatives you've considered**

**Additional context**

**Comment by badri-pathak** [comment]
PR to support this feature: [feature to support password rotation](https://github.com/IBM/ibm-spectrum-scale-csi/pull/1130)

**Comment by hemalathagajendran** [comment]
@badri-pathak Please close this issue as it got delivered in 2.12.
