### ISSUE TITLE
Remove image options from ibm-spectrum-scale-csi-operator-cr.yaml file

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#117]
**Describe the bug**

**To Reproduce**

We should remove below options from "https://github.com/IBM/ibm-spectrum-scale-csi/blob/master/operator/deploy/crds/ibm-spectrum-scale-csi-operator-cr.yaml" as we have mechanism using env variable to set these images for testing/dev now. This will help us restricting user to not try untested attacher,provisioner,driver-registrar,scale driver images. Scale driver images are hard-coded and matched with operator code.
```
# Attacher image name, in case we do not want to use default image.
# ==================================================================================
#  attacher: "quay.io/k8scsi/csi-attacher:v1.0.0"

# Provisioner image name, in case we do not want to use default image.
# ==================================================================================
#  provisioner: "quay.io/k8scsi/csi-provisioner:v1.0.0"

# Driver Registrar image name, in case we do not want to use default image.
# ==================================================================================
#  driverRegistrar: "quay.io/k8scsi/csi-node-driver-registrar:v1.0.1'"

# SpectrumScale CSI Plugin image name, in case we do not want to use default image.
# ==================================================================================
#  spectrumScale: "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v1.0.0"
```

**Expected behavior**
Remove image options from ibm-spectrum-scale-csi-operator-cr.yaml file

**Comment by smitaraut** [comment]
We do need a way to override images for customers who do not have internet access from clusters. If env vars is the way to set these then that is fine too, but we'll need some user documentation on how to use it.

**Comment by Jainbrt** [comment]
Hi Smita, I agree to override images alteast for testing env which is already there in the dev yaml ( I hope) but for customers who do not have internet access from production clusters, cann't they download the required images offline and  load them to local openshift repository because today evan OCP 4.3 installation happens that way.

**Comment by mew2057** [comment]
I don't think I want to remove the interface from the CR, because I personally think we should leave that option open, because the Environment can _easily_ be overridden. We provide the environment so we can have a different delivery stream for test and RC. Generally speaking I view the use case for the Custom  Resource Settings as being a mechanism for the  user to lock their config in place via CR.

**Comment by Jainbrt** [comment]
Hi Team, I hope we are not targeting this for 1.1.0 so removing the 1.1.0 milestone.

**Comment by deeghuge** [comment]
We decided to keep image option as is. Closing this as no action required.
