### ISSUE TITLE
Attaching of PVC in pod should not user restAPI to query  FS mount status

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#128]
**Is your feature request related to a problem? Please describe.**
CSI driver needs to determine Filesystem is mounted on worker node during PVC attachment/mount to pod while pod is starting.  Currently it is using restAPI to query mount status. It has few issues: 
1. GUI is single point of failure, so pod would not start if GUI is down. I think it is big issue. 
2. We have observed that GUI does not refresh mount status frequently and it is possible that GUI incorrectly report FS is not mounted.

**Describe the solution you'd like**
mount query should not depend on restAPI.

**Comment by mew2057** [comment]
If my understanding of the driver is correct, I'm not sure if  this is  possible, because the Rest API  should be considered the source of truth.

I'm not entirely sure on the current design, however, @deeghuge should have more knowledge of this.

**Comment by deeghuge** [comment]
@gandhisanjayv : Yes agree with your analysis but shouldn't we fixing the REST api rather than keep using workaround for any such issues.

**Comment by gandhisanjayv** [comment]
this would considered as a single point of failure in mount path and few customers has requirement that mount path should not have single point of failure due o GUI node. 
@aspalazz

**Comment by deeghuge** [comment]
There is no plan to move away from the REST API for checking mount status. There is enhancement planned for GUI HA which will help reduce the severity of this concern. Closing as there is no plan to move from REST and GUI HA is tracked as new enhancement.
