### ISSUE TITLE
csiscaleoperators.csi.ibm.com.cr.yaml should have comment for If Kubernetes node name starts with a number,

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#135]
**Describe the bug**
KC has comment

https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_config_kubernet_SS_mapping_procedure_final.html

```
If Kubernetes node name starts with a number, then add node mapping for such nodes in this format:


    - k8sNode: "K8sNodePrefix_<Kubernetes Node Name/ID>"
      spectrumscaleNode: "<Spectrum Scale Node Name/ID>"
Copy

For example, if Kubernetes node name is 192.168.122.11, then use the following node mapping:


    - k8sNode: "K8sNodePrefix_192.168.122.11"
      spectrumscaleNode: "spectrumscalenode11"

```
**To Reproduce**
1. ...

**Expected behavior**

**Environment**
Please run the following an paste your output here:
``` bash
# Developement
operator-sdk version 
go version

# Deployment
kubectl version
rpm -qa | grep gpfs
```
**Screenshots**

**Additional context**

**Comment by smitaraut** [comment]
This issue is for changing the cr file and not documentation, hence labeling it as "Bug"
