### ISSUE TITLE
provide way to verify  images in quay

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#152]
**Is your feature request related to a problem? Please describe.**
we need way to verify images in quay is correct.  This is a similar to verifying gold master on spectrum scale, We document md5sum for package. 

**Describe the solution you'd like**
Evan suggested following
checking what is uploaded to quay, then you might want to know the build ID, git commit, git tag/version, etc
**Describe alternatives you've considered**

**Additional context**
nstalled v1.1.0 on openshift 4.2 via OLM.  it pulled following images. how to verify that images are correct?
ibm-spectrum-scale-csi-driver 8b6cb1a1743e
ibm-spectrum-scale-csi-operator ced0267b0a45
(edited)

Evan Dunn:working_remotely_0671922247:  2 hours ago
not sure what you mean, or are trying to accomplish
but here is how docker works -
docker manifest inspect quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator:v1.1.0
this is the fat manifest and lists the manifests per platform
if you take the linux/amd64 manifest and then inspect that...
docker manifest inspect quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator@sha256:6dfeb08e2e377efc147f9a5b793ac0dbaecc9c1e1a3bafb9a6170d7ab97326c0 
notice: you have to reference the manifest by digest as that is how the fat manifest references it
this platform specific manifest then has the digest of the image itself
"digest": "sha256:ced0267b0a4537376ff677f5c25b0532c69896aedd44ffc3f18b9150728ba927"
and you can see that matches with what you list (you are showing the truncated hash)

Evan Dunn:working_remotely_0671922247:  2 hours ago
this doesn't really serve much purpose as we could easily enough swap the tag to some other manifest (aka what I did to add z & p to the x only manifest)
tags are just references to the digest, digests reference a manifest or an underlying image
from the OLM perspective John has it pointed to just the v1.1.0 tag -- not the digest itself

Sanjay Gandhi  2 hours ago
I wanted to validate that images uploaded on quay is correct and OLM is pulling correct images . I don’t know it is required for docker images  but we use md5cksum for rpms.

Evan Dunn:working_remotely_0671922247:  2 hours ago
the digest is the sha256 of the image, so its akin to checking md5

Evan Dunn:working_remotely_0671922247:  2 hours ago
for checking what is uploaded to quay, then you might want to know the build ID, git commit, git tag/version, etc
sadly, we don't dynamically add that -- we should

**Comment by mew2057** [comment]
Implemented a fix for this which adds a `git_commit`  label to both the driver and operator images.

**Comment by mew2057** [comment]
Solution has  been merged.
