### ISSUE TITLE
Changes to cluster definition are not propagated to the  StatefulSets

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#173]
**Describe the bug**
If  a change is made to the `cluster` section of the CR the  change is not reflected in the  StatefulSets.

**To Reproduce**
1. Deploy the operator with a CR.
2. Change the `guiHost`
3. StatefulSets  remains unchanged.

**Expected behavior**
A change to guihost should reinitialize the StatefulSets.

**Possible Solution**
Implement the StatefulSets with the Cluster Checksum used in the DaemonSets.

**Comment by deeghuge** [comment]
@mew2057 : Sorry but I didn't not understand why we need to restart Statefulset when there are changes in CR for guihost ? 

Or you mean restart the statefulSet when changes in CR like image name and nodeSelector.

**Comment by mew2057** [comment]
Reviewing the initial cause of this issue, I'm thinking it's a non-issue. Closing and cancelling PR.
