### ISSUE TITLE
Remove documentation on manual OLM depoyment from yaml files from mainline doc path

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#18]
Now that the operator is in OperatorHub and RedHat, we should remove the documentation in the README.md and related files regarding the steps for deploying the operator via OLM using `apply -f` of the yaml files.

That more of a developer topic than an end user topic.

**Comment by mew2057** [comment]
@whowutwut  what's the status on this? I know we did a ton of documentation updates.

**Comment by whowutwut** [comment]
Let's close this one, I think we addressed and streamlined the doc for now, let's see if any one opens issues in the future.
