### ISSUE TITLE
Create labels for scale nodes automatically

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#192]
As for now, if I have nodes with and without scale, I need to manually create labels for CSI pods so that they run on scale nodes only:

`oc label node worker1 scale=true --overwrite=true`

This could be performed automatically with the Node Feature Discovery. Probably, you would need to use functionality provided by the NFD operator (https://github.com/openshift/cluster-nfd-operator). 

Please investigate if you could discover scale nodes and automatically assign labels.

**Comment by mew2057** [comment]
To better understand this request, these nodes have  scale installed a priori to execution of the operator?

**Comment by przem123** [comment]
yes, exactly, nodes have already scale installed before the csi operator is deployed.

**Comment by deeghuge** [comment]
I feel this requirement is for CNSS not for CSI Driver.

**Comment by deeghuge** [comment]
This is implemented as part of CNSA-CSI integration
