### ISSUE TITLE
" oc get csidrivers.storage.k8s.io" does not show scale csi driver details

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#197]
**Describe the bug**
" oc get csidrivers.storage.k8s.io" does not show scale csi driver details

**To Reproduce**
```
[root@oc-w3 ~]# oc get csidrivers.storage.k8s.io
No resources found in ibm-spectrum-scale-csi-driver namespace.
```

**Expected behavior**
" oc get csidrivers.storage.k8s.io" should show scale csi driver details

**Environment**
OCP 4.4.4

**Comment by mew2057** [comment]
This doesn't work in `kubernetes` either. @deeghuge or @dunnevan  do we know what this is supposed to contain in a describe.

**Comment by deeghuge** [comment]
I think it is good to have feature not an issue. 
https://kubernetes-csi.github.io/docs/csi-driver-object.html
