### ISSUE TITLE
Make primaryFset, clusterId and scaleHostpath params optional in driver configuration yaml file

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#20]
When I create an instance of a CSI driver, I need to edit a yaml file. There, I need to specify `primaryFset` and `scaleHostpath`. 

I would expect that if I do not specify `primaryFset` then the driver/operator would create automatically a generic fset in my filesystem. 

For `scaleHostpath`, the operator/ driver could obtain it from the Spectrum Scale GUI via REST API, so I think you should not require the user to remember and insert the path. 

Can you make both of the parameters optional ? This would simplify the configuration.

**Comment by deeghuge** [comment]
- we can not go away from scaleHostpath, It is design limitation. 
- removing clusterId at this stage will attract major changes in design
- primaryFset is valid requirement and can be implemented

**Comment by gandhisanjayv** [comment]
will it impact upgrade and restart of csi driver?  it tries to creates primaryFset during csi driver pod start.

**Comment by deeghuge** [comment]
@gandhisanjayv 
> will it impact upgrade and restart of csi driver? it tries to creates primaryFset during csi driver pod start.

It will not impact the upgrade because for older deployment primaryFset was there and it will be continue to be there after upgrade and provided value will be used. 
For new deployment if primaryFset is not given, fileset will be created using default fileset name and if given it will use the specified name.

**Comment by gandhisanjayv** [comment]
how do we ensure that default fileset name is not managed by other user?

**Comment by deeghuge** [comment]
> how do we ensure that default fileset name is not managed by other user?
We are documenting the default name. current default name we are thinking of is spectrum-scale-csi-volume-store.

**Comment by Jainbrt** [comment]
@deeghuge fixed in 2.0.0, we can close this now.
