### ISSUE TITLE
All Pods Stuck in ContainerCreating Due to Volumes Not Mounting

### ISSUE THREAD

**Issue by tristan-le** [IBM/ibm-spectrum-scale-csi#215]
**Bug Description**
We launched system stress tests for fileset and lightweight provisioning on an **OpenShift** cluster that has 8 worker nodes.

For the fileset provisioning: We originally ran fileset with 16 deployments, 1 pod per deployment, and 62 pvcs each, with a goal to test 1000 fileset pvc. The pods were stuck in ContainerCreating. We then ran a smaller version with 1 deployment, 1 pod per deployment, and 10 pvcs, which also resulted in a pod stuck in ContainerCreating:

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/66130947/83308156-0ac72100-a1bb-11ea-97d6-5b4d92eeef4c.png">

We then tried to launch lightweight provisioning (1 deployment, 3 pod per deployment, and 1 pvc), which is also resulted in all pods stuck in ContainerCreating:

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/66130947/83308298-64c7e680-a1bb-11ea-8a0b-ca8e1aa09442.png">

Worker nodes have the following CPU and memory utilization:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/66130947/83308524-c8eaaa80-a1bb-11ea-9d39-9b0ba161432e.png">

The problem does not appear to be stress related.

Deleting the pod results in redeployment, but it is also stuck in ContainerCreating.

Description of pods show the following errors:

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/66130947/83308789-71990a00-a1bc-11ea-9a7c-ea52f7e564a9.png">

**To Reproduce**
A stress test of fileset or lightweight provisioning of pod(s) with one or more pvc should demonstrate this.

**Expected behavior**
There should not be any pods stuck in ContainerCreating. If so, a deleting of the pod should cause the deployment to launch one that can run.

**Environment**
CSI 2.0.0 (Downloaded 5/28/20)

<img width="731" alt="image" src="https://user-images.githubusercontent.com/66130947/83309088-33501a80-a1bd-11ea-8f39-7bd37eee482d.png">

**Additional context**
A snap of the logs is resident on the system (Armstrong):
/ibm/ibm1/CSI/CSI-2.0.0-tools/ibm-spectrum-scale-csi/tools/ibm-spectrum-scale-csi-logs_05-29-2020-08:15:35

**Comment by deeghuge** [comment]
Hi @tristan-le, 
I don't find logs at location you mentioned. 

[root@armstrong-compute1 CSI]# ls -l /ibm/ibm1/CSI
total 375696
-rw-r--r--. 1 root root 96101888 Nov  7  2019 csi-spectrum-scale_v0.9.1.tar
-rw-r--r--. 1 root root 96242688 Oct 25  2019 csi-spectrum-scale_v0.9.1.tar.old

**Comment by MonicaLemay** [comment]
[root@armstrong-inf ibm-spectrum-scale-csi-logs_05-29-2020-08:15:35]# pwd
/ibm/ibm1/CSI/CSI-2.0.0-tools/ibm-spectrum-scale-csi/tools/ibm-spectrum-scale-csi-logs_05-29-2020-08:15:35

**Comment by deeghuge** [comment]
When I checked the all pods were running. Can you please help me with steps to recreate the issue on Armstrong cluster ?

**Comment by tristan-le** [comment]
On armstrong-compute1 (9.11.137.149), PWD: /ibm/ibm1/blast, includes all files required to build the blast image.

Attached is the launcher that launches the blast image, creates the storage class, pvcs, deployments. (I added the .pdf to be able to attach, please let me know if the file was corrupted in the process.)

[launch_fileset_blast_root.ksh.pdf](https://github.com/IBM/ibm-spectrum-scale-csi/files/4713147/launch_fileset_blast_root.ksh.pdf)

**Comment by tristan-le** [comment]
Monica found the problem. The problem was a reuse of the location of /blast in the pod for execution AND for mounting a pvc volume on /blast. A big hint and tip came from Deepak getting a simpler deployment/pod to run. And thank you to Aaron P. for running a 'dmesg | grep blast' to reveal segfaults. Moving blast logs to a pvc that mounts to /BlastLogs and kept execution in /blast solves the problem.
