### ISSUE TITLE
Define imagePullSecret placeholder in operator.yaml 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#216]
**Describe the bug**
We should define imagePullSecret placeholder in operator.yaml and as well as instruction how to update that with image secret in KC. 

**Expected behavior**
Define imagePullSecret placeholder in operator.yaml

**Comment by mew2057** [comment]
I don't know how useful this will be. The secret will match the user's environment, so a default is not strictly necessary. Additionally, `imagePullSecrets` are not in our critical path, so there's less importance to have a default.

**Comment by mew2057** [comment]
Misread this, I actually don't believe that this should be   in the yaml file at all. This is native k8s, we shouldn't document native k8s operations.
