### ISSUE TITLE
Need to handle old driver registration socket file after 1.0.1 -> 2.0.0 and delete after driver uninstall

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#218]
**Describe the bug**
Need to handle old driver registration socket file after 1.0.1 -> 2.0.0 and delete after driver uninstall

**To Reproduce**

1. After upgrade from 1.0.1 -> 2.0.0, `oc get csinodes` shows old driver name too
```
[root@oc-w3 configfile]# oc get csinodes.storage.k8s.io  oc-w3.ocp.openshift.scale.net -o yaml
apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  creationTimestamp: "2019-10-19T20:44:56Z"
  name: oc-w3.ocp.openshift.scale.net
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: oc-w3.ocp.openshift.scale.net
    uid: 5804bc48-f2aa-11e9-a0df-005056a1cd5b
  resourceVersion: "92705271"
  selfLink: /apis/storage.k8s.io/v1/csinodes/oc-w3.ocp.openshift.scale.net
  uid: 4f503fc8-f2b1-11e9-a0df-005056a1cd5b
spec:
  drivers:
  - name: ibm-spectrum-scale-csi
    nodeID: oc-w3.ocp.openshift.scale.net
    topologyKeys: null
  - name: spectrumscale.csi.ibm.com
    nodeID: oc-w3.ocp.openshift.scale.net
    topologyKeys: null


[root@oc-w3 configfile]# ls -ltr /var/lib/kubelet/plugins_registry/
total 0
srwx------. 1 root root 0 May 21 19:00 ibm-spectrum-scale-csi-reg.sock
srwx------. 1 root root 0 Jun  1 14:21 spectrumscale.csi.ibm.com-reg.sock

```

Note : we should clean the reg.sock file in `/var/lib/kubelet/plugins_registry/` dir.

**Expected behavior**
Need to clean old ibm-spectrum-scale-csi-reg.sock file in `/var/lib/kubelet/plugins_registry/` after upgrade from 1.0.1 -> 2.0.0 and `spectrumscale.csi.ibm.com-reg.sock` after 2.0.0 uninstall

**Environment**
Please run the following an paste your output here:
``` bash
OCP 4.4.4
GPFS 5.0.5
```

**Comment by deeghuge** [comment]
@Jainbrt Can we close this one ?

**Comment by madhuthorat** [comment]
This looks to be low priority, it looks difficult to work on this for 2.5.0

**Comment by Jainbrt** [comment]
old releases are now not supported,so closing this defect
