### ISSUE TITLE
Add a proper form for CSI driver for Openshift 4

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#22]
When I create CSI driver instances with the Operator I must adjust the yaml file. Openshift 4 offers a possibility to edit a form version instead. Maybe you could adjust the yaml file so that it would match the form ? This would be much easier and user friendly than manually editing the yaml file as it shows required fields in a nice UI.

**Comment by Jainbrt** [comment]
We did improved CSI instance UI view in CSI 2.4.0, @przem123 you can check and suggest us further changes

**Comment by deeghuge** [comment]
Closing since UI is improved significantly. Please reopen if there are more improvement needed
