### ISSUE TITLE
Pod Stuck in ContainerCreating Despite PVC Bound

### ISSUE THREAD

**Issue by tristan-le** [IBM/ibm-spectrum-scale-csi#223]
**Bug Description**
We launched a system stress test of 1 million files in a PVC on an **OpenShift** cluster that has 8 worker nodes.

The 1 million files in a PVC was run with 1 deployment, 1 pod, and 2 PVC (one contains the files and the other for Blast), with a goal of creating 1 million files nested in the PVC.

The pod is stuck in 'ContainerCreating' despite the PVCs required being 'Bound'. The script does check that a PVC is 'Bound' before proceeding to the creation of the next PVC and before creating a deployment.

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/66130947/83908513-16b36580-a71c-11ea-97ec-24367063853a.png">

A describe on the stuck pod shows the following errors:

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/66130947/83908871-a9540480-a71c-11ea-8b4c-67ed3294358e.png">

While the pod is stuck in 'ContainerCreating', the PVCs are 'Bound' and their requisite Spectrum Scale fileset exist and are 'Linked'.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/66130947/83908719-6db93a80-a71c-11ea-9234-329f4982068b.png">

Sometimes the pod will become 'Running' hours later. It might be stress related. We ran a sanity check on a non-stressed vanilla Kubernetes on CSI 1.0.0 and had no problems. We plan to run this test again on a non-stressed/stressed vanilla Kubernetes cluster on CSI 2.0.0.

**To Reproduce**
Launch script found on armstrong-inf at PWD: /ibm/ibm1/CSI_dynamic_scripts/filesets/launch_fileset_blast_root.ksh

**Expected behavior**
Pod should go to 'Running', rather then stay in 'ContainerCreating', when all prerequisites are created and running properly.

**Environment**
CSI 2.0.0 (Downloaded 5/28/20)

<img width="586" alt="image" src="https://user-images.githubusercontent.com/66130947/83909536-d654e700-a71d-11ea-8d96-49185bb76e6b.png">

**Additional context**
A snap of the logs is resident on the system (armstrong-inf), PWD: /ibm/ibm1/CSI/CSI-2.0.0-tools/ibm-spectrum-scale-csi/tools/ibm-spectrum-scale-csi-logs_06-05-2020-11:15:35

**Comment by smitaraut** [comment]
The pod is attempting to mount on armstrong-compute7 and I see below logs in /var/log/messages on that node for the relevant PVC-

```
Jun  5 06:46:23 armstrong-compute7 hyperkube: I0605 06:46:23.500263    1943 volume_manager.go:372] Waiting for volumes to attach and mount for pod "test1mil-blast-deployment1-597df5779c-qshs6_test1mil-namespace(025b4f66-c203-45ce-b165-499d00046621)"
Jun  5 06:46:23 armstrong-compute7 hyperkube: I0605 06:46:23.537185    1943 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-5d70ae72-3c83-4de5-9f65-f2d4a2e5232d" (UniqueName: "kubernetes.io/csi/spectrumscale.csi.ibm.com^9972787030613075382;090B8949:5DAF5B91;fileset=3;path=/ibm/ibm1/csifset1/.volumes/pvc-5d70ae72-3c83-4de5-9f65-f2d4a2e5232d") pod "test1mil-blast-deployment1-597df5779c-qshs6" (UID: "025b4f66-c203-45ce-b165-499d00046621")
Jun  5 06:46:23 armstrong-compute7 hyperkube: E0605 06:46:23.537373    1943 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/spectrumscale.csi.ibm.com^9972787030613075382;090B8949:5DAF5B91;fileset=3;path=/ibm/ibm1/csifset1/.volumes/pvc-5d70ae72-3c83-4de5-9f65-f2d4a2e5232d\"" failed. No retries permitted until 2020-06-05 06:46:24.037281776 -0700 MST m=+1520372.011389724 (durationBeforeRetry 500ms). Error: "Volume has not been added to the list of VolumesInUse in the node's volume status for volume \"pvc-5d70ae72-3c83-4de5-9f65-f2d4a2e5232d\" (UniqueName: \"kubernetes.io/csi/spectrumscale.csi.ibm.com^9972787030613075382;090B8949:5DAF5B91;fileset=3;path=/ibm/ibm1/csifset1/.volumes/pvc-5d70ae72-3c83-4de5-9f65-f2d4a2e5232d\") pod \"test1mil-blast-deployment1-597df5779c-qshs6\" (UID: \"025b4f66-c203-45ce-b165-499d00046621\") "
```

Notice this error from kubelet- **_Volume has not been added to the list of VolumesInUse in the node's volume status for volume_**

One of the remediation for this is given at https://www.ibm.com/support/knowledgecenter/en/SS6JWS_3.5.0/UG/sc_ug_troubleshooting_ub.html - to restart the controller manager pod. Can you please try that see if it fixes the issue?

**Comment by tristan-le** [comment]
Please assist us in identifying which pod is the controller-manager. There are 8 of them running on the Open Shift master nodes but there are none running on the compute node, armstrong-compute7.

**Comment by deeghuge** [comment]
This will list controller manager which are running on master nodes
`kubectl get pod -n openshift-kube-controller-manager | grep Running`

**Comment by smitaraut** [comment]
I see the pod test1mil-blast-deployment1-597df5779c-qshs6 in running state now. Was the kube-controller-manager restarted?

**Comment by MonicaLemay** [comment]
It was not restarted b/c we did not know which kube-controller-manager to restart.  There were several.   WE have seen in the past, that eventually,  after hours/days the pod will go to running.

**Comment by MonicaLemay** [comment]
I restarted all 3 kube-controller-manager pods and I don't see the problem anymore.
