### ISSUE TITLE
React to GRPC response failures

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#23]
```
I1022 16:09:27.285217       1 connection.go:235] GRPC call: /csi.v1.Identity/Probe
I1022 16:09:27.285251       1 connection.go:236] GRPC request:
I1022 16:09:27.285330       1 connection.go:238] GRPC response:
I1022 16:09:27.285357       1 connection.go:239] GRPC error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
I1022 16:09:27.285847       1 main.go:214] Probe failed with rpc error: code = Unavailable desc = all SubConns are in TransientFailure
```

I was testing an olm deployment by hand and I noticed the above error in the `attacher`. I'm still doing an RCA, but it looks like the secret wasn't present at container creation.

To resolve this better in the future we need to do several things:
1. Detect connection issues in containers.
2. Trigger events on certain error types (this might be event correlation in the controller).
3. Repair any errors possible.
4. If errors persist stop the container and call an admin.

**Comment by deeghuge** [comment]
Closing since this old issue and we haven't seen this issue in recent time. Please reopen if you face issue again
