### ISSUE TITLE
Dynmaic PVC get hanging on waiting for a volume to be created, either by external provisioner "spectrumscale.csi.ibm.com" or manually created by system administrator

### ISSUE THREAD

**Issue by Issen007** [IBM/ibm-spectrum-scale-csi#244]
**Describe the bug**

**To Reproduce**
1. I have create a basic Spectrum Scale Filesystem with pool name "k8s" with a fileset call "pvfileset"
2. Installed the CSI 2.0 driver via Openshift Operator Installer
3. Create a user in Spectrum Scale called csiAdmin and with a password.
4. create a secret key in Openshift by the documentation that comes with the operator installer. 
5. Run following script from the documentation to create a storage class.
`apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: scale
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "k8s"
    volDirBasePath: "pvfileset/"
reclaimPolicy: Delete
`
6. Create a PVC
`
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scale-fset-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: scale
`

Now it waiting for me to create the PVC manually. 

**Expected behavior**
I expect that Openshift can create a volume when a PVC is request a new volume

**Environment**
Please run the following an paste your output here:
```
$ oc version
Client Version: 4.3.13
Server Version: 4.4.9
Kubernetes Version: v1.17.1+912792b

# rpm -qa |grep gpfs
gpfs.license.adv-5.0.5-0.x86_64
gpfs.docs-5.0.5-0.noarch
gpfs.gss.pmcollector-5.0.5-0.el7.x86_64
gpfs.kafka-5.0.5-0.x86_64
gpfs.msg.en_US-5.0.5-0.noarch
gpfs.base-5.0.5-0.x86_64
gpfs.java-5.0.5-0.x86_64
gpfs.crypto-5.0.5-0.x86_64
gpfs.gskit-8.0.55-12.x86_64
gpfs.gss.pmsensors-5.0.5-0.el7.x86_64
gpfs.librdkafka-5.0.5-0.x86_64
gpfs.adv-5.0.5-0.x86_64
gpfs.gpl-5.0.5-0.noarch
gpfs.compression-5.0.5-0.x86_64
gpfs.gui-5.0.5-0.noarch
```
**Screenshots**
$ oc describe pvc
Name:          scale-fset-pvc
Namespace:     test
StorageClass:  scale
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"scale-fset-pvc","namespace":"test"},"spec":{"access...
               volume.beta.kubernetes.io/storage-provisioner: spectrumscale.csi.ibm.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    csi-scale-staticdemo-pod
Events:
  Type    Reason                Age               From                         Message
  ----    ------                ----              ----                         -------
  Normal  ExternalProvisioning  5s (x4 over 26s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "spectrumscale.csi.ibm.com" or manually created by system administrator

**Additional context**
This is playground test system and we just upgraded from Openshift 4.3 to Openshift 4.4.9

**Comment by Issen007** [comment]
Just want to say I sow this #204 and its report the same issue but only shows a code fix but nothing that explains the problem any why.
And I'm using version 2.0.0 of CSI Drivers so I guess the bug #204 is not solved then.

**Comment by deeghuge** [comment]
Hi @Issen007, Please share the logs by running [spectrum-scale-driver-snap.sh](https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/v2.0.0/tools/spectrum-scale-driver-snap.sh) script to debug the issue.

**Comment by Issen007** [comment]
Switching over to the Spectrum Scale CSI Driver Namespace:
```
$ oc project ibm-spectrum-scale-csi-driver
Now using project "ibm-spectrum-scale-csi-driver" on server "https://api.int.cristie.se:6443".
```

Running the script:
```
$ ./spectrum-scale-driver-snap.sh 
No resources found in ibm-spectrum-scale-csi-driver namespace.
ibm-spectrum-scale-csi driver and operator is not running in namespace ibm-spectrum-scale-csi-driver. Please provide a valid namespace
```

List PODs in the `ibm-spectrum-scale-csi-driver` namespace:
```
$ oc get pods
NAME                                               READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-operator-56df88b6bd-hqq9c   1/1     Running   0          5d17h
```

Run a describe on the Operator in that namespace.
```
$ oc describe pod
Name:         ibm-spectrum-scale-csi-operator-56df88b6bd-hqq9c
Namespace:    ibm-spectrum-scale-csi-driver
Priority:     0
Node:         compute-2.int.cristie.se/192.168.99.196
Start Time:   Tue, 23 Jun 2020 15:46:49 +0200
Labels:       app.kubernetes.io/instance=ibm-spectrum-scale-csi-operator
              app.kubernetes.io/managed-by=ibm-spectrum-scale-csi-operator
              app.kubernetes.io/name=ibm-spectrum-scale-csi-operator
              name=ibm-spectrum-scale-csi-operator
              pod-template-hash=56df88b6bd
              product=ibm-spectrum-scale-csi
              release=ibm-spectrum-scale-csi-operator
Annotations:  alm-examples:
                [{"status": {}, "kind": "CSIScaleOperator", "spec": {"provisionerNodeSelector":[{"key": "scale", "value": "true"}], "clusters":[{"secrets"...
              capabilities: Basic Install
              categories: Storage
              certified: false
              containerImage: registry.connect.redhat.com/ibm/ibm-spectrum-scale-csi-operator:v2.0.0
              createdAt: Tue Jun  9 11:18:01 EDT 2020
              description: An operator for deploying and managing the IBM CSI Spectrum Scale Driver.
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.129.2.10"
                    ],
                    "dns": {},
                    "default-route": [
                        "10.129.2.1"
                    ]
                }]
              olm.operatorGroup: ibm-spectrum-scale-csi-driver-nhjwf
              olm.operatorNamespace: ibm-spectrum-scale-csi-driver
              olm.targetNamespaces: ibm-spectrum-scale-csi-driver
              openshift.io/scc: anyuid
              productID: ibm-spectrum-scale-csi-operator
              productName: IBM Spectrum Scale CSI Operator
              productVersion: 2.0.0
              repository: https://github.com/IBM/ibm-spectrum-scale-csi/
              support: IBM
Status:       Running
IP:           10.129.2.10
IPs:
  IP:           10.129.2.10
Controlled By:  ReplicaSet/ibm-spectrum-scale-csi-operator-56df88b6bd
Containers:
  operator:
    Container ID:   cri-o://87083ac15774a27c498d098554c62ee69e06a3173ba080bb5584655bc2a29187
    Image:          registry.connect.redhat.com/ibm/ibm-spectrum-scale-csi-operator:v2.0.0
    Image ID:       registry.connect.redhat.com/ibm/ibm-spectrum-scale-csi-operator@sha256:3330e32a8247b4989828490323499bb5d84b638545a2fd8f1184ac5c5016e199
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 23 Jun 2020 15:47:17 +0200
    Ready:          True
    Restart Count:  0
    Liveness:       exec [./health_check.sh] delay=10s timeout=1s period=30s #success=1 #failure=3
    Readiness:      exec [./health_check.sh] delay=3s timeout=1s period=1s #success=1 #failure=3
    Environment:
      WATCH_NAMESPACE:   (v1:metadata.annotations['olm.targetNamespaces'])
      POD_NAME:         ibm-spectrum-scale-csi-operator-56df88b6bd-hqq9c (v1:metadata.name)
      OPERATOR_NAME:    ibm-spectrum-scale-csi-operator
    Mounts:
      /tmp/ansible-operator/runner from runner (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-spectrum-scale-csi-operator-token-fcvw2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  runner:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  ibm-spectrum-scale-csi-operator-token-fcvw2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ibm-spectrum-scale-csi-operator-token-fcvw2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

**Comment by deeghuge** [comment]
As per output only operator pod is running. seems like driver pods are not yet running/started which likely cause the PVC creation pending issue. 

Please pass logs of following command to confirm If driver is deployed or not
`oc get daemonset -n ibm-spectrum-scale-csi-driver`
`oc get statefulset -n ibm-spectrum-scale-csi-driver`

**Comment by Issen007** [comment]
Shows nothing.
```
$ oc get daemonset -n ibm-spectrum-scale-csi-driver
No resources found in ibm-spectrum-scale-csi-driver namespace.
$ oc get statefulset -n ibm-spectrum-scale-csi-driver
No resources found in ibm-spectrum-scale-csi-driver namespace.
```

**Comment by deeghuge** [comment]
Hi @Issen007, 

I assume you followed all the steps documented [here](https://www.ibm.com/support/knowledgecenter/STXKQY_CSI_SHR/com.ibm.spectrum.scale.csi.v2r00.doc/bl1csi_install_usingOLM.html). I suspect step k is not fully complete. Please recheck once.
Also pass the output of  `oc -n ibm-spectrum-scale-csi-driver logs ibm-spectrum-scale-csi-operator-56df88b6bd-hqq9c`

**Comment by Issen007** [comment]
I Found this is in the documentation.
https://www.ibm.com/support/knowledgecenter/STXKQY_CSI_SHR/com.ibm.spectrum.scale.csi.v2r00.doc/bl1csi_planning_hwswreq.html

Does the CSI driver only run on a RHEL Worker noder? I only have CoreOS Worker nodes at the moment.

**Comment by deeghuge** [comment]
>Does the CSI driver only run on a RHEL Worker noder?
Yes, Currently IBM Spectrum Scale CSI Driver is supported with only RHEL worker nodes.

**Comment by Issen007** [comment]
I'll will then migrate all our worker node from CoreOS to RHEL when I'm back from vacation.

**Comment by Issen007** [comment]
@deeghuge now have I moved all our nodes to RHEL Worker nodes and removed all our CoreOS Worker Nodes.
But still the same problem. 
```
$ oc get daemonset -n ibm-spectrum-scale-csi-driver
NAME                     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
ibm-spectrum-scale-csi   3         3         0       3            0           scale=true      6d6h

$ oc get statefulset -n ibm-spectrum-scale-csi-driver
NAME                                 READY   AGE
ibm-spectrum-scale-csi-attacher      1/1     6d6h
ibm-spectrum-scale-csi-provisioner   1/1     6d6h
´´´

**Comment by Issen007** [comment]
```
 oc -n ibm-spectrum-scale-csi-driver get pods
NAME                                              READY   STATUS                 RESTARTS   AGE
ibm-spectrum-scale-csi-79h9x                      1/2     CreateContainerError   1182       6d6h
ibm-spectrum-scale-csi-attacher-0                 1/1     Running                0          6d6h
ibm-spectrum-scale-csi-ns8h7                      1/2     CreateContainerError   1182       6d6h
ibm-spectrum-scale-csi-operator-76988dbf6-rkqh4   1/1     Running                0          6d6h
ibm-spectrum-scale-csi-p65s8                      1/2     CreateContainerError   1182       6d6h
ibm-spectrum-scale-csi-provisioner-0              1/1     Running                0          6d6h

$ oc -n ibm-spectrum-scale-csi-driver logs ibm-spectrum-scale-csi-p65s8
Error from server (BadRequest): a container name must be specified for pod ibm-spectrum-scale-csi-p65s8, choose one of: [driver-registrar ibm-spectrum-scale-csi]
```

**Comment by Issen007** [comment]
Found the issue. The filesystem on my worker nodes wasn't mounted correct.
