### ISSUE TITLE
Need provision for non-default snapshot controller sidecar in the CR file

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#250]
**Describe the bug**
Need provision for non-default snapshot controller sidecar in the CR file

**To Reproduce**

1. Need provision for non-default snapshot controller sidecar in the CR file for new installation 
2. Need steps to use non-default snapshot controller sidecar in upgrade process 

**Expected behavior**
Need provision for non-default snapshot controller sidecar in the CR file

**Environment**
Please run the following an paste your output here:
``` 
OCP 4.4.4
```

**Comment by deeghuge** [comment]
@Jainbrt : What is expected here ?
We can specify the snapshotter in CR. Right ? Anything apart from this ?

**Comment by Jainbrt** [comment]
@deeghuge we do not have section in Cr.yaml file snapshotter sidecar image. `https://github.com/IBM/ibm-spectrum-scale-csi/blob/dev/operator/deploy/crds/csiscaleoperators.csi.ibm.com_cr.yaml`

**Comment by deeghuge** [comment]
@Jainbrt Please check if this can be closed
