### ISSUE TITLE
Need support for v1 API for CRD objects 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#256]
**Describe the bug**
we need support for v1 API for CRD objects as betav1 CRD will not be available in k8s 1.22 version 

**To Reproduce**
we need support for v1 API for CRD objects as betav1 CRD will not be available in k8s 1.22 version

**Expected behavior**
Need support for v1 API for CRD objects

**Comment by mew2057** [comment]
I have it implemented here:
https://github.com/mew2057/ibm-spectrum-scale-csi/tree/crd_v1

But the build is failing on molecule, not sure what's happening, because we clear the linting test.
https://travis-ci.com/github/mew2057/ibm-spectrum-scale-csi/jobs/360634923

**Comment by Jainbrt** [comment]
Verified on below image:
```
quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:704b6ef546ce949d3567174df542afd41e5e320c4c70efe02359778d937b7c49
quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:221c9ffe46ba82415d2b1f8449aa5aa6135ec487129e078e1270e4a764b0e20f
```

**Comment by Jainbrt** [comment]
As we are moving back to v1beta1 in release 2.1.0, reopening this issue for future tracking of CRD v1 work

**Comment by Jainbrt** [comment]
Closing as this has been fixed
