### ISSUE TITLE
Describe how to use the image with podman

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#27]
Please describe how to use the CSI image with podman.

**Comment by smitaraut** [comment]
The images are available on quay registry and are pulled by the operator. You dont need to use podman or docker to use them. Please see install instructions here-
https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_install_usingops.html
