### ISSUE TITLE
Placeholder, discuss the image Pull policy and the build process

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#28]
Just wanted to create this issue placeholder to discuss with @mew2057 after the US holiday this week.  Currently the pull policy is `imagePullPolicy: IfNotPresent` and we will not be pulling down later images of the container builds, if we already pulled it down at some point. 

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/10049070/69581303-4aab1280-0fa4-11ea-8e4f-828e43308885.png">

I think we have to decide:
* Is this the right pull policy? 
* Should we not be tagging over itself? 

I don't think we want to checkout a tag, but then also modify the yamls to point to the right tag to get..I'd like to be able to check out tags of this project and re-lauch the container with what is in the source code. If we are building over tags, and it doesn't get incremented, we will not be able to checkout and re-create the env..   

Example: 
```
git checkout 1.0.0 -> then `apply -f` files to deploy 
git checkout 1.0.1 -> then `apply -f` files to deploy  
git checkout 0.9.2 -> then `apply -f` files to deploy  
```

Or even have scripts that will `curl` down based on the tag version... , for example the `v0.9.0` tag...  https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi-operator/v0.9.0/stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/olm-scripts/operator-source.yaml

**Comment by Jainbrt** [comment]
@mew2057 I agree with you that we should have image pull policy to Ifnotpresent for GA builds as they don't change and for developers/testers we already have dev.yaml file where we have set image pull policy to Always. In that sense, is this defect still valid ?

**Comment by deeghuge** [comment]
We have `imagePullPolicy: IfNotPresent` policy for Production/Release yaml and `imagePullPolicy: Always` for dev yaml. So further fix required.
