### ISSUE TITLE
slow speed of snapshot creation from CSI to Scale

### ISSUE THREAD

**Issue by kulkarnicr** [IBM/ibm-spectrum-scale-csi#280]
**Describe the bug**

I was trying out a test - 256 snapshots on a PVC. It took minimum 7 minutes to create 256 snapshots on Scale.

To ensure, whether this delay is due to Scale, I tried out following two tests on local Scale GUI node itself:
1. created 256 snapshots sequentially - got over in 2 min 45 sec.
2. created 256 snapshots using 8 processes (each process creating 32 snapshots) - done in 1 min 47 sec.

This proves that Scale has the ability to create snapshots faster than what is seen from CSI node.

Can CSI snapshot (kubectl create volumesnapshot) utilize the real capability/speed of Scale snapshot creation (mmcrsnapshot) ?

I agree, CSI wont be able to match the speed of local Scale node. 
However, if possible, we can search whether there is any bottleneck from CSI/GUI side and fix/remove it to speed up things.

Please note this issue is only for the time frame required to create snapshots on Scale node itself (i.e. time difference between "mmcrsnapshot ... RC=0" log entries for 256th snapshot and 1st snapshot) i.e. I'm talking about how CSI feeds in snapshot create requests to Scale node and is there any scope of improvement?

**To Reproduce**
1. From CSI node, create 256 snapshots against a PVC. Check the time required to create 256 snapshots on Scale (I checked time difference between mmcrsnapshot /var/log/message entries for 1st snapshot and 256th snapshot).

```
=> took 7 min 25 sec (I've seen this minimum 7 mins required consistently on my fyre cluster.)

Jul 30 05:10:30 snivels4 mmfs[19453]: REST-CLI root csiadmin [EXIT, CHANGE] 'mmcrsnapshot fs1 pvc-bddeda79-eba9-49a9-a5cd-476219f204fd:snapshot-7de18e77-5136-4301-85e4-81ecae864d86' RC=0
...
Jul 30 05:17:55 snivels4 mmfs[16416]: REST-CLI root csiadmin [EXIT, CHANGE] 'mmcrsnapshot fs1 pvc-bddeda79-eba9-49a9-a5cd-476219f204fd:snapshot-c15102ea-27a6-4a2c-9fb1-e8209a9d0a58' RC=0
```

2. Sequentially Try 256 snapshots creation on local Scale node and check time required for it.

```
=> 1 process creating 256 snapshots) - 2 min 45 sec

Jul 30 03:14:35 snivels4 mmfs[13728]: CLI root root [EXIT, CHANGE] 'mmcrsnapshot fs1 pvc-975a7d90-87b6-4590-9772-c170da7588fc:snap1' RC=0
...
Jul 30 03:17:20 snivels4 mmfs[15254]: CLI root root [EXIT, CHANGE] 'mmcrsnapshot fs1 pvc-975a7d90-87b6-4590-9772-c170da7588fc:snap256' RC=0
```

3. Try 256 snapshots creation on local Scale node and check time required for it.

```
=> Parallel 8 process creating 256 snapshots - 1 min 45 sec

Jul 30 03:33:04 snivels4 mmfs[23168]: CLI root root [EXIT, CHANGE] 'mmcrsnapshot fs1 pvc-7c944f2e-c0e6-4102-9525-71af2ee37a44:33' RC=0
...
Jul 30 03:34:51 snivels4 mmfs[22668]: CLI root root [EXIT, CHANGE] 'mmcrsnapshot fs1 pvc-7c944f2e-c0e6-4102-9525-71af2ee37a44:224' RC=0
```

**Expected behavior**
We should improve snapshot creation speed from CSI to Scale.

**Environment**
Please run the following an paste your output here:
``` bash
# Developement
operator-sdk version 
go version

# Deployment
kubectl version
rpm -qa | grep gpfs

[root@snivels1 2020_07_30-05:50:21 20200728]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
[root@snivels1 2020_07_30-05:50:25 20200728]$
[root@snivels4 2020_07_30-05:50:40 ~]$ rpm -qa | grep gpfs
gpfs.msg.en_US-5.0.5-2.noarch
gpfs.java-5.0.5-2.x86_64
gpfs.license.adv-5.0.5-2.x86_64
gpfs.gss.pmcollector-5.0.5-2.el7.x86_64
gpfs.gpl-5.0.5-2.noarch
gpfs.docs-5.0.5-2.noarch
gpfs.compression-5.0.5-2.x86_64
gpfs.callhome-ecc-client-5.0.5-2.noarch
gpfs.crypto-5.0.5-2.x86_64
gpfs.gss.pmsensors-5.0.5-2.el7.x86_64
gpfs.gui-5.0.5-2.noarch
gpfs.librdkafka-5.0.5-2.x86_64
gpfs.base-5.0.5-2.x86_64
gpfs.gskit-8.0.55-12.x86_64
gpfs.adv-5.0.5-2.x86_64
gpfs.kafka-5.0.5-2.x86_64
[root@snivels4 2020_07_30-05:50:44 ~]$
```
**Screenshots**

**Additional context**

**Comment by deeghuge** [comment]
Hi @kulkarnicr, Few things we should consider in this comparison. 
1. Each CreateSnapshot request result in 6 different REST call to GUI that to sequential. 
2. CSI make use of rest API for Creating Snapshot
3. Overhead of Kubernetes while sending request to CSI Driver.

**Comment by kulkarnicr** [comment]
referred the comment from @deeghuge on Jul 31, 2020. 
It explains various components/APIs involved in CSI snapshot creation that contribute to delay. I don't have the data to validate how much time is involved through each component, hence closing the defect for now.

In case performance drops considerably for CSI snapshot creation in future, then I'll open separate issue.
