### ISSUE TITLE
ppc64le Kubernetes Operator Pod Error

### ISSUE THREAD

**Issue by tristan-le** [IBM/ibm-spectrum-scale-csi#286]
**Bug Description**
Installing the dev build of CSI 2.1.0 with latest Operator YAML results in an Operator Pod which crashes.

The Operator Pod will go through a continuous cycle from Running to Error to CrashLoopBackOff to Running...

This has happened on two Kubernetes clusters, one x86_64 and the other ppc64le.

On Astra (ppc64le):
<img width="962" alt="image" src="https://user-images.githubusercontent.com/66130947/89677377-309b3100-d8a2-11ea-8697-5889ef7e3b56.png">

Here is a describe of the Operator Pod on Astra (ppc64le):
<img width="956" alt="image" src="https://user-images.githubusercontent.com/66130947/89677465-588a9480-d8a2-11ea-8b95-d4701102f0e4.png">

This is the result when a 'kubectl logs' is run on the Operator Pod on Astra (ppc64le):
<img width="962" alt="image" src="https://user-images.githubusercontent.com/66130947/89677631-a7382e80-d8a2-11ea-9c36-c4eaf4e3b069.png">

**To Reproduce**
1. Apply Operator YAML from https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/dev/generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml

**Expected behavior**
The expected behavior is for the Operator Pod to begin Running with no restarts.

**Environment**
<img width="958" alt="image" src="https://user-images.githubusercontent.com/66130947/89677781-e6667f80-d8a2-11ea-9298-32944972e1cb.png">

**Additional context**
A snap of the logs is resident on the system (astra3), PWD: /var/gpfs/fs0/CSI/CSI-2.1.0-030820/ibm-spectrum-scale-csi/tools/ibm-spectrum-scale-csi-logs_08-07-2020-11:43:53

**Comment by deeghuge** [comment]
Hi @tristan-le, 
Please try using following images for operator and driver 
`quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator-ppc64le:dev`
`quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver-ppc64le:dev`

**Comment by tristan-le** [comment]
I had previously used the '-ppc64le' images to the same result, but tried again today to see if it would take this time. It looks like the same erroring cycle is occurring.

This was the final state of the non '-ppc64le' operator images I had applied originally, notice number of restarts (1000+):
<img width="747" alt="image" src="https://user-images.githubusercontent.com/66130947/89797817-40a05400-dae0-11ea-9e86-7d699b153968.png">

These are the images I used this morning (includes '-ppc64le'):
<img width="846" alt="image" src="https://user-images.githubusercontent.com/66130947/89797523-e1424400-dadf-11ea-85b4-369cadc42719.png">

The Operator Pod is going through the same erroring cycle (Running/Error/CrashLoopBackOff), it had done this 5 times at this point:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/66130947/89797623-fc14b880-dadf-11ea-95f6-8070da5357b5.png">

These are the Events listed from a describe of the Operator Pod:
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/66130947/89797959-6fb6c580-dae0-11ea-99ef-907673b7282e.png">

These are the logs of the Operator Pod:
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/66130947/89798253-cc19e500-dae0-11ea-98a4-e24c7123ddad.png">

**Comment by smitaraut** [comment]
@tristan-le did you get this working? Is this still an issue?

**Comment by tristan-le** [comment]
@smitaraut Aaron and I were able to get a pretty stable operator pod onto the system. The next problem is application of a CR yaml causes the operator pod to crash. Should I make a new issue?

**Comment by tristan-le** [comment]
We were able to deploy a Fyre cluster that was Power/RHEL 7/K8s 1.19.2 and get CSI properly installed with the following:

In the Operator YAML -
A snapshotter was appended and was the only difference between this yaml and the official yaml.

``` bash
[root@koi-p-master CSI-2.1.0-230920]# diff ibm-spectrum-scale-csi-operator-dev-snapshots.yaml ibm-spectrum-scale-csi-operator-dev.yaml 
378,380d377
<                 snapshotter:
<                   description: Snapshotter image for csi (issues volume snapshot requests).
<                   type: string
```
The following images were used:

```bash
[root@koi-p-master CSI-2.1.0-230920]# cat ibm-spectrum-scale-csi-operator-dev-snapshots.yaml | grep quay
              value: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver-ppc64le:dev
          image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator-ppc64le:dev
```

In the CR YAML -
The following sidecars were used:

``` bash
[root@koi-p-master CSI-2.1.0-230920]# cat csiscaleoperators.csi.ibm.com_cr.yaml | egrep 'attacher|provisioner|driverRegistrar|snapshotter' | grep us
  attacher: "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-attacher:v3.0.0"
  provisioner: "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-provisioner:v2.0.0"
  driverRegistrar: "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-node-driver-registrar:v2.0.0"
  snapshotter: "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-snapshotter:v3.0.0"
```

In the Snapshot-Controller YAML-
The following image was used:

``` bash
[root@koi-p-master CSI-2.1.0-230920]# cat setup-snapshot-controller.yaml | grep image:
          image: us.gcr.io/k8s-artifacts-prod/sig-storage/snapshot-controller:v3.0.0
```
