### ISSUE TITLE
[OCP] Using the olm script manually to apply does not work in OpenShift environment (no marketplace namespace)

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#29]
**Describe the bug**

Trying to follow this instruction:  
![image](https://user-images.githubusercontent.com/10049070/69446966-7ec3d080-0d23-11ea-9fe7-dcaa60de2edc.png)

Results in this error: 

```
clusterrolebinding.rbac.authorization.k8s.io/olm-crb created
Error from server (NotFound): error when creating "deploy/olm-scripts/operator-source.yaml": namespaces "marketplace" not found
Error from server (NotFound): error when creating "deploy/olm-scripts/operator-source.yaml": namespaces "marketplace" not found
Error from server (NotFound): error when creating "deploy/olm-scripts/operator-source.yaml": namespaces "marketplace" not found
No resources found.
```

**To Reproduce**

In Openshift environment, run `oc apply -f deploy/olm-scripts/operator-source.yaml` 

**Expected behavior**

Operator comes up? 

**Environment**

Running this code: 
```
[root@c943f4n01-pvt csi-operator-ansible]# cd ~/go/src/github.com/IBM/ibm-spectrum-scale-csi-operator/
[root@c943f4n01-pvt ibm-spectrum-scale-csi-operator]# git remote -v
origin	https://github.com/IBM/ibm-spectrum-scale-csi-operator.git (fetch)
origin	https://github.com/IBM/ibm-spectrum-scale-csi-operator.git (push)
[root@c943f4n01-pvt ibm-spectrum-scale-csi-operator]# git branch
* dev
[root@c943f4n01-pvt ibm-spectrum-scale-csi-operator]# git  log -1
commit be2ca36225d6fc5760b69a0595c4a709be7eaf7e
Merge: 3303227 9b1057c
Author: John Dunham <JFDBEar1@gmail.com>
Date:   Thu Nov 21 17:22:08 2019 -0500

    Merge pull request IBM/ibm-spectrum-scale-csi-operator#60 from mew2057/csv-vet

    Cluster Service Version Cleanup
```

**Screenshots**

**Additional context**

**Comment by smitaraut** [comment]
This should have been addressed with the GA. OLM instructions here-
https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_install_usingOLM.html

**Comment by deeghuge** [comment]
Following document provide the mechanism for OLM pre release test. 
https://github.com/IBM/ibm-spectrum-scale-csi/blob/dev/tools/ansible/olmupgrade.md

Please reopen if above document is not sufficient
