### ISSUE TITLE
Sample storage classes with correct backend, clusterID  should be created after deploy.

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#297]
**Is your feature request related to a problem? Please describe.**
Currenlty customer has to create yaml files for storage class. Creating sample yaml files for specific deploy will help to provide better end-to-end experience.  I think it would be even good to create storage class by default for dynamic fileset provisioning. 
**Describe the solution you'd like**
Create storage class yaml files or storage classes.
Provide customized  readme file for lightweight provisioning and dependent filesets.
wow factor: Create all type of storage classes after deploy so that PVC's can be created from GUI console using this storage classes.
**Describe alternatives you've considered**

**Additional context**

**Comment by smitaraut** [comment]
Sample manifests are provided here and cover all scenarios-
[https://github.com/IBM/ibm-spectrum-scale-csi/tree/master/driver/examples](https://github.com/IBM/ibm-spectrum-scale-csi/tree/master/driver/examples)

I dont think sample storageclass creation should be part of plugin initialization or deployment. CSI driver wont know what kind of storageclasses are needed. If at all it is needed for some end-to-end solution, then that solution should implement this outside of CSI driver.

**Comment by deeghuge** [comment]
Closing since It is taken care as part of CNSA-CSI integration.
