### ISSUE TITLE
add new testcase to verify bind mount

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#298]
**Is your feature request related to a problem? Please describe.**
It was fixed in 5.1.0.x RTC  217029
Testcase:
create PVCs and attach to pods
check bind mounts using gpfs-namespace-mounts.py. script, it should show all bind mounts
mmumount filesytem 
inject error: mmmount filesystem. ( should able to mount)
verify that PVC can be attached from pods
Repeat above with inject error: mmshutdown

**Comment by deeghuge** [comment]
@Jainbrt is there anything needs to be done for this one ?
