### ISSUE TITLE
1.6.10 - Operators status section must provide meaningful information

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#31]
The operator Status  section needs to be enhanced to provide more details.

**Comment by gandhisanjayv** [comment]
"kubectl rollout history "    should also provide relevant info. 

kubectl rollout history  deployment ibm-spectrum-scale-csi-operator -n ibm-spectrum-scale-csi-driver
deployment.apps/ibm-spectrum-scale-csi-operator
REVISION  CHANGE-CAUSE
1         <none>
2         <none>
3         <none>
4         <none>

Ref:
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#checking-rollout-history-of-a-deployment

**Comment by mew2057** [comment]
Dropping 1.1.0  release target and reducing severity, current iteration is fine  doesn't need more work for the 1.1.0 release

**Comment by madhuthorat** [comment]
Duplicate of #536
