### ISSUE TITLE
After some time, daemon sets are being re-deployed for no apparent reason

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#32]
**Describe the bug**

After the operator brings up the driver, leaving for a few hours,  we  see that the AGE of the statefulsets and the daemonsets are not in sync, despite no changes done to the cluster. 

Here's the pods showing the age difference

```
[root@c943f4n01-pvt csi-operator-ansible]# ./operator-helper.sh get_pods
+ oc get pods -n ibm-spectrum-scale-csi-driver
NAME                                               READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-8t9k2                       2/2     Running   0          32m
ibm-spectrum-scale-csi-attacher-0                  1/1     Running   0          4h56m
ibm-spectrum-scale-csi-operator-6ff9cf6979-k2gpd   2/2     Running   0          4h56m
ibm-spectrum-scale-csi-provisioner-0               1/1     Running   0          4h56m
ibm-spectrum-scale-csi-tcml4                       2/2     Running   0          32m
ibm-spectrum-scale-csi-x8nf6                       2/2     Running   0          32m
+ set +x
```

**To Reproduce**

1. Deploy the operator 
2. use the operator to deploy driver..
3. Wait... and check pods. 

**Expected behavior**

The age should not change when nothing is triggering changes to the yaml files

**Environment**

Running the following container images

```
    Image:          quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator:v0.9.2
    Image ID:       quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator@sha256:cbb83684dbf172bba95e7914a0685808880dedd033daa43e736778b59cd946b8
    Image:         quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v0.9.1
    Image ID:      quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:e5926978bd4f4a553df18fc79ac532037c4e31e3a2cdaa6a5c06014fba02c808
```

**Screenshots**

**Additional context**

**Comment by mew2057** [comment]
This  is super stale at this point, @whowutwut have you seen this recently?

**Comment by mew2057** [comment]
I think this one is cleared, it had something to do with the secret code and it should  have been fixed by the secret code  fix.

**Comment by whowutwut** [comment]
Thanks for cleaning this up, i don't think i have seen it recently.
