### ISSUE TITLE
OLM upgrade from v2.0.0 - v2.1.0 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#322]
**Describe the bug**
Need templates for OLM upgrade from v2.0.0 - v2.1.0 

**To Reproduce**
OLM upgrade from v2.0.0 - v2.1.0 

**Expected behavior**
Need templates for OLM upgrade from v2.0.0 - v2.1.0

**Comment by deeghuge** [comment]
Fixed and Verified hence closing.
