### ISSUE TITLE
pod stuck in  CreateContainerError  when using replicas

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-spectrum-scale-csi#337]
I have several pods stuck in :
[root@lightfury-inf creation_of_pvc_and_deployments]# oc get pods -A |grep blast | grep  Cont*
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf                      0/1     CreateContainerError   0          131m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d4462j9db                      0/1     CreateContainerError   0          131m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d4462tljz                      0/1     CreateContainerError   0          131m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d4464g78r                      0/1     CreateContainerError   0          131m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d44656m2m                      0/1     CreateContainerError   0          132m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446895nv                      0/1     CreateContainerError   0          131m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446c78c4                      0/1     CreateContainerError   0          130m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446djrm7                      0/1     CreateContainerError   0          132m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446flfkr                      0/1     CreateContainerError   0          130m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446gf9g7                      0/1     CreateContainerError   0          130m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446hd247                      0/1     CreateContainerError   0          132m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446kvzqq                      0/1     CreateContainerError   0          130m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446msppz                      0/1     CreateContainerError   0          131m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446p2hfq                      0/1     CreateContainerError   0          132m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446sgwgv                      0/1     CreateContainerError   0          132m
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d446sm6ld                      0/1     CreateContainerError   0          131m
[root@lightfury-inf creation_of_pvc_and_deployments]#

When I describe them I see this error:
test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf

[root@lightfury-inf creation_of_pvc_and_deployments]# oc describe pod -n test-blast1-namespace                              test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf
Name:         test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf
Namespace:    test-blast1-namespace
Priority:     0
Node:         lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com/9.11.226.164
Start Time:   Thu, 08 Oct 2020 12:19:12 -0700
Labels:       app=blast-write-loopapp
              pod-template-hash=79958d446
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.130.2.17"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.130.2.17"
                    ],
                    "default": true,
                    "dns": {}
                }]
              openshift.io/scc: scale-gui-restricted
Status:       Pending
IP:           10.130.2.17
IPs:
  IP:           10.130.2.17
Controlled By:  ReplicaSet/test-blast1-fileset-blast-write-loop-deployment1-79958d446
Containers:
  test-blast1-fileset-blast-write-loop-container1:
    Container ID:
    Image:         localhost/blast-write-loop:latest
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /blast-write-loop/blast-write-loop_script.sh
      -p
      5
      -t
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data1 from vol1 (rw)
      /data2 from vol2 (rw)
      /data3 from vol3 (rw)
      /data4 from vol4 (rw)
      /data5 from vol5 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-w4qwv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  vol1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  test-blast1-fileset-dplmnt1-pvc1
    ReadOnly:   false
  vol2:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  test-blast1-fileset-dplmnt1-pvc2
    ReadOnly:   false
  vol3:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  test-blast1-fileset-dplmnt1-pvc3
    ReadOnly:   false
  vol4:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  test-blast1-fileset-dplmnt1-pvc4
    ReadOnly:   false
  vol5:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  test-blast1-fileset-dplmnt1-pvc5
    ReadOnly:   false
  default-token-w4qwv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-w4qwv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                                                                  Message
  ----     ------                  ----                  ----                                                                  -------
  Normal   SuccessfulAttachVolume  133m                  attachdetach-controller                                               AttachVolume.Attach succeeded for volume "pvc-891aaff0-118a-4877-9a65-c9ff782b3c34"
  Normal   SuccessfulAttachVolume  133m                  attachdetach-controller                                               AttachVolume.Attach succeeded for volume "pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0"
  Normal   SuccessfulAttachVolume  133m                  attachdetach-controller                                               AttachVolume.Attach succeeded for volume "pvc-cba7087f-838a-4b53-bcd7-ce321a43265f"
  Normal   SuccessfulAttachVolume  133m                  attachdetach-controller                                               AttachVolume.Attach succeeded for volume "pvc-2d25c786-7c91-4388-b103-86f2552b49f0"
  Normal   SuccessfulAttachVolume  133m                  attachdetach-controller                                               AttachVolume.Attach succeeded for volume "pvc-04b98a3f-8aa9-40c1-bf03-d425eb7f7ec2"
  Normal   Scheduled               133m                  default-scheduler                                                     Successfully assigned test-blast1-namespace/test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf to lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com
  Normal   AddedInterface          132m                  multus                                                                Add eth0 [10.130.2.17/23]
  Warning  Failed                  130m                  kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: reserving container name: error reserving ctr name k8s_test-blast1-fileset-blast-write-loop-container1_test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf_test-blast1-namespace_5867f87a-b6e4-4ee6-81eb-49be98d0fe1f_0 for id 99906e0e236ad572a650178cfe8373cec2a97b19a01fe528e9bed661c4f69ce7: name is reserved
  Warning  Failed                  130m                  kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: reserving container name: error reserving ctr name k8s_test-blast1-fileset-blast-write-loop-container1_test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf_test-blast1-namespace_5867f87a-b6e4-4ee6-81eb-49be98d0fe1f_0 for id 39b0f658696c00b7321e728163bf94b864bf79d0f9f5603831f4eb162ad1fc87: name is reserved
  Warning  Failed                  130m                  kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: reserving container name: error reserving ctr name k8s_test-blast1-fileset-blast-write-loop-container1_test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf_test-blast1-namespace_5867f87a-b6e4-4ee6-81eb-49be98d0fe1f_0 for id 7536752406c8f46d059bfcadd918514fdd7a3374d259eed6a93b66f85021d89f: name is reserved
  Warning  Failed                  130m                  kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: reserving container name: error reserving ctr name k8s_test-blast1-fileset-blast-write-loop-container1_test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf_test-blast1-namespace_5867f87a-b6e4-4ee6-81eb-49be98d0fe1f_0 for id d30e74f7b0d7b35ceb81e9f31009a3f63a9f369c3ba0c7ce8191e1c827358390: name is reserved
  Warning  Failed                  129m                  kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: reserving container name: error reserving ctr name k8s_test-blast1-fileset-blast-write-loop-container1_test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf_test-blast1-namespace_5867f87a-b6e4-4ee6-81eb-49be98d0fe1f_0 for id d2a880db7d9cb068a3899dfa67911bc1ecf749b7b2d6c8d2700f65d2cc2e0af6: name is reserved
  Warning  Failed                  129m                  kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: reserving container name: error reserving ctr name k8s_test-blast1-fileset-blast-write-loop-container1_test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf_test-blast1-namespace_5867f87a-b6e4-4ee6-81eb-49be98d0fe1f_0 for id 3e02e9f28b35c91266b4cbef849bd9528b9b927eafcbf349e503ce5b7608c662: name is reserved
  Warning  Failed                  129m                  kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: reserving container name: error reserving ctr name k8s_test-blast1-fileset-blast-write-loop-container1_test-blast1-fileset-blast-write-loop-deployment1-79958d4462h4bf_test-blast1-namespace_5867f87a-b6e4-4ee6-81eb-49be98d0fe1f_0 for id 0714e5abe5484e7f34b8502037ce26504d95f43c02309c7281bad9fd88ecebf2: name is reserved
  Warning  Failed                  129m                  kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: relabel failed /var/mnt/fs2/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0-data: lstat /var/mnt/fs2/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0-data/test-blast1-fileset-blast-write-loop-deployment1-79958d4468dmll_60_20-10-07-22:41:35.122116494/tiny/test0/f34.blt: no such file or directory
  Normal   Pulled                  92m (x42 over 132m)   kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Container image "localhost/blast-write-loop:latest" already present on machine
  Warning  Failed                  47m (x2 over 86m)     kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: relabel failed /var/mnt/fs2/pvc-cba7087f-838a-4b53-bcd7-ce321a43265f/pvc-cba7087f-838a-4b53-bcd7-ce321a43265f-data: lstat /var/mnt/fs2/pvc-cba7087f-838a-4b53-bcd7-ce321a43265f/pvc-cba7087f-838a-4b53-bcd7-ce321a43265f-data/test-blast1-fileset-blast-write-loop-deployment1-79958d446kzhxm_46_20-10-07-22:41:36.294705027/tiny/test0/f37.blt: input/output error
  Warning  Failed                  17m (x7 over 116m)    kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: relabel failed /var/mnt/fs2/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0-data: lstat /var/mnt/fs2/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0-data/test-blast1-fileset-blast-write-loop-deployment1-79958d446zlgth_83_20-10-07-22:41:34.651676995/tiny/test0/f996.blt: input/output error
  Warning  Failed                  7m8s (x87 over 127m)  kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  (combined from similar events): Error: relabel failed /var/mnt/fs2/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0-data: failed to set file label on /var/mnt/fs2/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0/pvc-c4cd6f97-02af-4694-a1fb-9638817e4fd0-data/test-blast1-fileset-blast-write-loop-deployment1-79958d446r6fh6_44_20-10-07-22:41:36.138679776/tiny/test0/f72.blt: invalid argument
  Warning  Failed                  116s (x18 over 130m)  kubelet, lightfury-compute11.lightfury.scale-ocp.tuc.stglabs.ibm.com  Error: context deadline exceeded
[root@lightfury-inf creation_of_pvc_and_deployments]#

Can someone explain what these errors mean.  The mentiong of test0/<some_file>.blt is odd.  I have never seen the mention of a file that is supposed to be written by the I/O container throw up an error here.

**Comment by deeghuge** [comment]
Hi @MonicaLemay, Please reopen if you see this again. At initial look it doesn't look like CSI issue.
