### ISSUE TITLE
All pods not deleted when ran `kubectl label node <nodename> scale-` command 

### ISSUE THREAD

**Issue by nilbante** [IBM/ibm-spectrum-scale-csi#360]
We were trying  Upgrade path testing for CNSA on OCP 4.6. Ran below steps
1. Installed OCP 4.5
2. Installed CNSA
3. Installed CSI
4. Followed https://www-03preprod.ibm.com/support/knowledgecenter/STXKQY_CNSS_review/maintenance/shut-down.html link to shutdown CNSA
5. First ran `oc adm drain <node1> <node2> --ignore-daemonsets=true --delete-local-data=true`
6. and then `kubectl label node <nodename> scale-`
This should delete CSI pod as well. but when checked volume status they were still running

```
[root@gsanjay-2021-1-inf Nilesh]# oc get nodes -l=node-role.kubernetes.io/worker=   -ojsonpath="{range .items[*]}{'Node: '}{.metadata.name}{'\n'}\
  {'Volumes Attached\n'}{.status.volumesAttached}{'\n'}\
  {'Volumes In Use\n'}{.status.volumesInUse}{'\n\n'}"
Node: worker0.gsanjay-2021-1.cp.fyre.ibm.com
  Volumes Attached

  Volumes In Use


Node: worker1.gsanjay-2021-1.cp.fyre.ibm.com
  Volumes Attached

  Volumes In Use


Node: worker2.gsanjay-2021-1.cp.fyre.ibm.com
  Volumes Attached
[map[devicePath: name:kubernetes.io/csi/spectrumscale.csi.ibm.com^26792029077282077;0A0B5292:5FF69DEC;filesetName=pvc-cda1977a-18be-4b85-81c8-8c9a8e07bf23;path=/mnt/nilfs1/spectrum-scale-csi-volume-store/.volumes/pvc-cda1977a-18be-4b85-81c8-8c9a8e07bf23]]
  Volumes In Use
[kubernetes.io/csi/spectrumscale.csi.ibm.com^26792029077282077;0A0B5292:5FF69DEC;filesetName=pvc-cda1977a-18be-4b85-81c8-8c9a8e07bf23;path=/mnt/nilfs1/spectrum-scale-csi-volume-store/.volumes/pvc-cda1977a-18be-4b85-81c8-8c9a8e07bf23]
```
Checked CSI pod status. They were still running
```
[root@gsanjay-2021-1-inf ~]# oc get pod
NAME                                               READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-attacher-0                  1/1     Running   1          19h
ibm-spectrum-scale-csi-operator-7764988654-p9wjr   1/1     Running   0          19h
ibm-spectrum-scale-csi-provisioner-0               1/1     Running   1          19h
test-csi-pod                                       1/1     Running   0          19h
[root@gsanjay-2021-1-inf ~]#
```
Logically they should got deleted (except operator one) with update of node label.

**Comment by nilbante** [comment]
In order successful verification of CNSA upgrade  in OCP 4.5=> 4.6 we ran below steps for CSI.
```
1. Updated nodes lable  'kubectl label node <nodename> scale-`
2. PVC was still showing in use and then deleted test-csi-pod.  
 It wasn't deleted since long time so ran force command to delete pod.
3. Make sure only operator, provisioner and attacher pod is running
4.  Started OCP upgrade from 4.5 => 4.6
5.  After successful finish of upgrade, ran kmod.yaml to update machine config, started CNSA and then CSI
6. Wait till all pods come up and then created test-csi-pod
7. Verified file created in test-csi-pod is reflected at storge host mount point.
```
Couple of questions: 1. Is there any documentation which say attacher, provisioner adn test-csi-pod wont be deleted after updating label of nodes?
2. Why do we need to delete test-csi-pod with force option?

fyi @gandhisanjayv

**Comment by Jainbrt** [comment]
> 
> 
> In order successful verification of CNSA upgrade in OCP 4.5=> 4.6 we ran below steps for CSI.
> 
> ```
> 1. Updated nodes lable  'kubectl label node <nodename> scale-`
> 2. PVC was still showing in use and then deleted test-csi-pod.  
>  It wasn't deleted since long time so ran force command to delete pod.
> 3. Make sure only operator, provisioner and attacher pod is running
> 4.  Started OCP upgrade from 4.5 => 4.6
> 5.  After successful finish of upgrade, ran kmod.yaml to update machine config, started CNSA and then CSI
> 6. Wait till all pods come up and then created test-csi-pod
> 7. Verified file created in test-csi-pod is reflected at storge host mount point.
> ```
> 
> Couple of questions: 1. Is there any documentation which say attacher, provisioner and test-csi-pod wont be deleted after updating label of nodes?
test-csi-pod is not a part of CSI deployment. 
attacher/provisioner are statefulset pod and they will not be deleted after label update because of kubernetes design.

> 2. Why do we need to delete test-csi-pod with force option?
Could you please provide more input in this test-csi-pod ?
> 
> fyi @gandhisanjayv

**Comment by nilbante** [comment]
> > In order successful verification of CNSA upgrade in OCP 4.5=> 4.6 we ran below steps for CSI.
> > ```
> > 1. Updated nodes lable  'kubectl label node <nodename> scale-`
> > 2. PVC was still showing in use and then deleted test-csi-pod.  
> >  It wasn't deleted since long time so ran force command to delete pod.
> > 3. Make sure only operator, provisioner and attacher pod is running
> > 4.  Started OCP upgrade from 4.5 => 4.6
> > 5.  After successful finish of upgrade, ran kmod.yaml to update machine config, started CNSA and then CSI
> > 6. Wait till all pods come up and then created test-csi-pod
> > 7. Verified file created in test-csi-pod is reflected at storge host mount point.
> > ```
> > 
> > 
> > Couple of questions: 1. Is there any documentation which say attacher, provisioner and test-csi-pod wont be deleted after updating label of nodes?
> > test-csi-pod is not a part of CSI deployment.
> > attacher/provisioner are statefulset pod and they will not be deleted after label update because of kubernetes design.
> 
> > 1. Why do we need to delete test-csi-pod with force option?
> >    Could you please provide more input in this test-csi-pod ?
I reproduced this again where test-csi-pod is failing to delete. I already shared cluster details via slack.  I performed below steps
1. Ran `oc label nodes -l node-role.kubernetes.io/worker= scale-`. Make sure csi core pods got deleted
2.  Then started deletion of test-csi-pod but its stuck at deletion
> > 
> > fyi @gandhisanjayv

**Comment by nilbante** [comment]
As per chat with Abhishek, test-csi pod is not part of deployment.
