### ISSUE TITLE
volumeSnapshot should not be created on below scale version (5.1.0.1)

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#364]
**Describe the bug**
volumeSnapshot should not be created on below scale version (5.1.0.1)

**To Reproduce**

volumeSnapshot should not be created on below scale version (5.1.0.1)

**Expected behavior**
volumeSnapshot creation should fail with proper error if created below scale version (5.1.0.1)

**Comment by madhuthorat** [comment]
The code changes were done only in driver (not operator). So for testing sharing just the driver image at quay.io/madhuthorat/ibm-spectrum-scale-csi-driver-dev:driver_issue364.

**Comment by madhuthorat** [comment]
Also for testing, one option for testing logic for version check is to run the portion of the patch which does version check at: https://play.golang.org/p/auCWHE0ARkg
Change the values here and test.

**Comment by madhuthorat** [comment]
@Jainbrt Can we close this ?
