### ISSUE TITLE
Refactor landing README for this project

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#37]
I'm running through the main README file and I'm making some changes to prepare submitting a Pull Request.  But as I run this, the refactoring may be a little more than what is expected, so I wanted to pitch an skeleton outline and get feedback from @mew2057   so we are on the  same page... 

I think there's two User Roles for the csi-operator and my thoughts on each..

* Developer that wants to help  - The README should be really  written to this user 
* Admin/Customer - They should go through OLM (Operator Lifecycle Management) and not see this repo

## Consumer 

This one is easier, they  should be going through this process to get the operator... 

* From OpenShift 
    * Operator -> OperatorHub 
    * Search scale-csi-operator 
    * Install and follow instructions
* From https://operatorhub.io/
    * search for scale-csi-operator
    * Install and follow instructions 

## Developer 

So the real audience for this README github project should be developers....  Here's my proposal of the  skeleton outline for the landing page README.md doc.... 

* Build from Source 
   * Clone
   * Build

* Deploy  
    * spectrum scale config file 
    * Create operator 
       * Repository (quay) - recommended   
          * `kubectl apply` - single file 
       * Manual (kubectl apply multiple files )
    * Destroy operator
       * Repository 
          * `kubectl delete` -  single file
       * Manual (kubectl delete multiple files )

I don't have the whole picture yet, so I might have mistaken something, but let's discuss

I haven't refactored yet, but working on smaller changes here: https://github.com/whowutwut/ibm-spectrum-scale-csi-operator/blob/readme_fix/README.md

**Comment by smitaraut** [comment]
- Consumers/Customers documentation is the IBM KnowledgeCenter - https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_kc_landing.html

- Developers/Contributors documentation should be on github

Lets use this issue to refactor the github docs or developer consumption.

**Comment by deeghuge** [comment]
@whowutwut : We have addressed most of the document concern in v1.1.0 release.
Apart from those are there any other action needs to taken on this topic? If not can we close the issue ?

**Comment by whowutwut** [comment]
I don't have a problem closing this issue.  Thanks for the reminder.
