### ISSUE TITLE
two CSI replicasets after upgrade of CSI

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#386]
**Describe the bug**
after upgrade of CSI from 2.1.0 to 2.2.0

```
[root@gsanjay-ocp47-inf ~]# oc get all
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/ibm-spectrum-scale-csi-9jszn                       2/2     Running   0          43h
pod/ibm-spectrum-scale-csi-attacher-0                  1/1     Running   1          43h
pod/ibm-spectrum-scale-csi-djx58                       2/2     Running   0          43h
pod/ibm-spectrum-scale-csi-operator-79799cc67b-g5pbv   1/1     Running   7          43h
pod/ibm-spectrum-scale-csi-provisioner-0               1/1     Running   1          43h
pod/ibm-spectrum-scale-csi-sckh8                       2/2     Running   0          43h
pod/ibm-spectrum-scale-csi-snapshotter-0               1/1     Running   2          43h
pod/ibm-spectrum-scale-csi-test-pod                    1/1     Running   0          43h
NAME                                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/ibm-spectrum-scale-csi-operator-metrics   ClusterIP   172.30.143.224   <none>        8383/TCP,8686/TCP   3d23h
NAME                                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/ibm-spectrum-scale-csi   3         3         3       3            3           scale=true      3d23h
NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ibm-spectrum-scale-csi-operator   1/1     1            1           3d23h
NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/ibm-spectrum-scale-csi-operator-67448f6956   0         0         0       3d23h
replicaset.apps/ibm-spectrum-scale-csi-operator-79799cc67b   1         1         1       43h
NAME                                                  READY   AGE
statefulset.apps/ibm-spectrum-scale-csi-attacher      1/1     3d23h
statefulset.apps/ibm-spectrum-scale-csi-provisioner   1/1     3d23h
statefulset.apps/ibm-spectrum-scale-csi-snapshotter   1/1     43h
[root@gsanjay-ocp47-inf ~]# cd /home/csi-instal
```

**To Reproduce**
upgrade from 2.1.0 to 2.2.0 using CLI method.

**Comment by madhuthorat** [comment]
This doesn't look to be a new issue. Could see the same issue when upgrading from 2.0.0 to 2.1.0 as well on a kubernetes 1.20 cluster.

# kubectl get all -n ibm-spectrum-scale-csi-driver
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/ibm-spectrum-scale-csi-attacher-0                  1/1     Running   0          2m21s
pod/ibm-spectrum-scale-csi-fplpj                       2/2     Running   0          66s
pod/ibm-spectrum-scale-csi-operator-67448f6956-pg9mm   1/1     Running   0          3m50s
pod/ibm-spectrum-scale-csi-provisioner-0               1/1     Running   0          2m21s
pod/ibm-spectrum-scale-csi-qc84d                       2/2     Running   0          111s
NAME                                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/ibm-spectrum-scale-csi-operator-metrics   ClusterIP   10.102.211.99   <none>        8383/TCP,8686/TCP   6m46s
NAME                                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/ibm-spectrum-scale-csi   2         2         2       2            2           scale=true      5m35s
NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ibm-spectrum-scale-csi-operator   1/1     1            1           7m9s
NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/ibm-spectrum-scale-csi-operator-67448f6956   1         1         1       3m50s
replicaset.apps/ibm-spectrum-scale-csi-operator-689bb9fbc8   0         0         0       7m9s
NAME                                                  READY   AGE
statefulset.apps/ibm-spectrum-scale-csi-attacher      1/1     5m42s
statefulset.apps/ibm-spectrum-scale-csi-provisioner   1/1     5m39s

**Comment by deeghuge** [comment]
This seems like working as designed.

**Comment by deeghuge** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
Closing as this seems like working as expected. Nothing we can do from CSI side.
