### ISSUE TITLE
collect relevent logs  incase of installation failure.

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#40]

**Comment by deeghuge** [comment]
@gandhisanjayv @Jainbrt : Can you please add more details about what logs are missing ?

**Comment by Jainbrt** [comment]
@deeghuge looks like this is pretty old issue when snap script was not there but @gandhisanjayv can add if there is anything to be added?

**Comment by deeghuge** [comment]
Closing since we have snap to collect all the logs. Please reopen if we still need any other logs with specific details
