### ISSUE TITLE
Nightly builds for the operator are not expiring like on the driver builds

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#41]
Just noticed on the nightly builds for the operator, the expiry time is not set. 

https://quay.io/repository/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator?tab=tags

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/10049070/73291968-387d6880-41cf-11ea-9816-87b7ed142b35.png">

**Comment by whowutwut** [comment]
```
    - IMAGE_LABEL=$(
        if [[ $TRAVIS_EVENT_TYPE == 'cron' ]];
        then
            echo "--label version=${IMAGE_VERSION} --label quay.expires-after=2w";
        else
            echo "--label version=${IMAGE_VERSION}";
        fi
      )
```
Are we not getting into this build as a "cron" type?  It should be shared code.

**Comment by dunnevan** [comment]
IMAGE_LABEL needs to be injected during docker build.  In operator-sdk build I think this can be done with --image-build-args '${IMAGE_LABEL}'

**Comment by dunnevan** [comment]
Step 9/9 : LABEL version=quay_op_expire

 ---> Running in abfdfe6482da

^ yep that works.
