### ISSUE TITLE
After running spectrum-scale-driver-snap.sh ,in output ibm-spectrum-scale-csi-describe-all-by-label file having some incorrect information

### ISSUE THREAD

**Issue by vrushch** [IBM/ibm-spectrum-scale-csi#410]
**Describe the bug**
ran spectrum-scale-driver-snap.sh , in output file ibm-spectrum-scale-csi-describe-all-by-label got following output at the end
```
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "external-provisioner-runner" not found
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "csi-provisioner-role" not found
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "external-attacher-runner" not found
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "csi-provisioner-role" not found
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "csi-nodeplugin" not found
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "csi-nodeplugin" not found

```
**To Reproduce**
1. Run spectrum-scale-driver-snap.sh file
2. In output directory , open ibm-spectrum-scale-csi-describe-all-by-label file and look at the end

**Expected behavior**
Server should not give error,  clusterrolebinding names maybe incorrect

**Comment by Jainbrt** [comment]
@vrushch Could you please verify the same with latest snap script ?

**Comment by vrushch** [comment]
Tried with latest snap script , Above problem seems fixed ( above error messages are not there). 
closing the issue
