### ISSUE TITLE
[Operator] Delete on invalid secret name hangs CR deletion

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#42]
**Describe the bug**
When deleting the CR for the operator if the secret is invalid it will  prevent the user from deleting their  custom resource.

**To Reproduce**
1. Create  a new Custom Resource.
 - This resource should have a bad secret name.
2. Attempt to delete the Custom Resource.

**Expected behavior**
The Custom Resources  should  be deleted, however, the  driver gets caught in `ContainerCreating` and the Custom Resource removal gets hung.

**Environment**

``` bash
# Developement
operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64"
go version go1.13.1 linux/amd64

# Deployment
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mew2057** [comment]
I'm not actually seeing the operator  ingest the  delete in the logs.

**Comment by mew2057** [comment]
@dunnevan @deeghuge, If we're missing the secret can that hang the driver image?

**Comment by mew2057** [comment]
Reviewing the task file and it  looks like the fix I made before the  consolidation didn't work. I think that  results is empty, so the logic needs to be  reworked.

```
- name: Ensure secret {{ item.secrets }} defined in {{ lookup( 'vars','namespace' ) }}
  k8s_facts:
    kind: secrets
    namespace: "{{ lookup( 'vars','namespace' ) }}"
    name : "{{ item.secrets }}"
  register: results
  failed_when: results is not defined
```

**Comment by mew2057** [comment]
I've updated the task so the failure check is now this:

```
failed_when: results is not defined or results.results is not defined or (results.results|length==0)
```

When  a bad secret is used, it will behave as follows:

```
TASK [csi-scale : Ensure secret secret123 defined in ibm-spectrum-scale-csi-driver] ***
task path: /opt/ansible/roles/csi-scale/tasks/cluster_check.yml:2
fatal: [localhost]: FAILED! => {"changed": false, "failed_when_result": true, "resources": []}

TASK [csi-scale : Assert cluster check failure is legal] ***********************
task path: /opt/ansible/roles/csi-scale/tasks/main.yml:25
fatal: [localhost]: FAILED! => {
    "assertion": "state != \"present\"",
    "changed": false,
    "evaluated_to": false,
    "msg": "Cluster check failed when setting state to present, exiting"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=1    ignored=0
```

I need to enhance the test case to check for this condition.

**Comment by mew2057** [comment]
Looks like even if we rescue this can cause major problems in the operator clean up. I _think_ if the CR gets rescues it dirties the custom resource.  Need to plan a work around this failure case. Might be a good time to work on #31 to handle this issue.

**Comment by mew2057** [comment]
Continuing to dig on the deletion:

```
     33 status:
     34   conditions:
     35   - lastTransitionTime: "2020-01-29T18:32:48Z"
     36     message: Running reconciliation
     37     reason: Running
     38     status: "False"
     39     type: Running
     40   - ansibleResult:
     41       changed: 0
     42       completion: 2020-01-29T18:33:59.387087
     43       failures: 0
     44       ok: 6
     45       skipped: 6
     46     lastTransitionTime: "2020-01-29T18:34:00Z"
     47     message: unknown playbook failure
     48     reason: Failed
     49     status: "True"
     50     type: Failure
```

It looks like the state is Failure it  refuses to remove the CR.

**Comment by mew2057** [comment]
```
PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0    skipped=6    rescued=1    ignored=0
```

Interestingly they don't grab rescues?

**Comment by mew2057** [comment]
```{"level":"info","ts":1580322840.3807209,"logger":"runner","msg":"Ansible-runner exited successfully","job":"2740103009342231109","name":"csi-scale-operator","namespace":"ibm-spectrum-scale-csi-driver"}```

It turns out that it executed clean?

**Comment by deeghuge** [comment]
> @dunnevan @deeghuge, If we're missing the secret can that hang the driver image deploy?

Not sure if this is still valid for this issue but JFYI - Secret is mounted as volume in scale csi container hence K8s will not start container unless it found the secret. The POD will remain in ContainerCreating state.
