### ISSUE TITLE
Pre-Installation Steps Errors

### ISSUE THREAD

**Issue by tristan-le** [IBM/ibm-spectrum-scale-csi#421]
**Description**
Certain CSI Knowledge Center Pre-Installation Tasks (https://www.ibm.com/docs/en/spectrum-scale-csi?topic=installation-performing-pre-tasks) are incomplete and inaccurate.

1. For the "Verify the file system configuration" task:

There are no instructions on how to set the Quota Value displayed in
```mmlsfs gpfs0 --filesetdf -Q --perfileset-quota```

Instructions should include command needed to set Quota Value prior to this task:
```mmchfs gpfs0 -Q yes```

2. For the "Enable quota for root user by issuing the following command" task:

The instructions include this command:
```mmlsconfig enforceFilesetQuotaOnRoot=yes```

The command should be:
```mmchconfig enforceFilesetQuotaOnRoot=yes```

3. For the "For Red Hat OpenShift, ensure that the controlSetxattrImmutableSELinux parameter is set to "yes" by issuing the following command" task:

The instructions include this command:
```mmlsconfig controlSetxattrImmutableSELinux=yes```

The command should be:
```mmchconfig controlSetxattrImmutableSELinux=yes```

**Comment by tristan-le** [comment]
Also, there is another KC error on the Secret instructions (https://www.ibm.com/docs/en/spectrum-scale-csi?topic=configurations-secrets#concept_pkl_ghh_53b).

For the "Create secret in the CSI namespace by issuing the following command" step:

The instructions include this command:

```kubectl create secret generic [secret_name] --from-literal=username=[gui_username] --from-literal=password=[gui_password] -n ibm-spectrum-scale-csi-driverCopy```

The command should be:

```kubectl create secret generic [secret_name] --from-literal=username=[gui_username] --from-literal=password=[gui_password] -n ibm-spectrum-scale-csi-driver```

**Comment by Jainbrt** [comment]
@tristan-le is there anything pending on this one?

**Comment by tristan-le** [comment]
I am waiting for the KC changes to be committed.

**Comment by tristan-le** [comment]
The Pre-Installation Steps were fixed here: https://www.ibm.com/docs/en/spectrum-scale-csi?topic=installation-performing-pre-tasks

And the Secret instructions were fixed here: https://www.ibm.com/docs/en/spectrum-scale-csi?topic=configurations-secrets#concept_pkl_ghh_53b

Closing the issue.
