### ISSUE TITLE
Snapshot of small PVC is twice the size of PVC

### ISSUE THREAD

**Issue by lanak01** [IBM/ibm-spectrum-scale-csi#422]
For  small PVCs, less than 10 Gi, the snapshot is twice the size of PVC.  The size of PVC restored form the snapshot is also twice the size of original PVC.

>oc get pvc 
scale-ns01-pvc000-1m   Bound    pvc-f143abc4-553e-4436-b66c-7e1753e99bc6   1Mi        RWO      

>oc get volumesnapshot
snapshot-test-pvc2          true         scale-ns01-pvc000-1m                           2Mi           ibm-spectrum-scale-snapshot-class  

> oc get pvc
scale-ns01-pvc000-1m            Bound    pvc-f143abc4-553e-4436-b66c-7e1753e99bc6   1Mi        RWO       
scale-ns01-pvc000-1m-restored   Bound    pvc-91cdcff6-8949-4e9b-ae11-7dbbee41174e   2Mi        RWO         

File system info:
[mmlsfs-info.log](https://github.com/IBM/ibm-spectrum-scale-csi/files/6473944/mmlsfs-info.log)

**Comment by gandhisanjayv** [comment]
Sanjay Gandhi  1:27 PM
so did you define 1M and it created 2M?





Lana Khorosheva  1:28 PM
Yes, but you need to specify the size of snapshot, not the size of original PVC.  If 1M is entered, getting this error:
failed to provision volume with StorageClass "scale-csi-independent-fileset": error getting handle for DataSource Type VolumeSnapshot by Name snapshot-test-pvc2: requested volume size 1048576 is less than the size 2097152 for the source snapshot snapshot-test-pvc2
1:29
No, I had to define 2M

**Comment by lanak01** [comment]
Upgraded CSI driver to 2.3.1 and no longer see this problem

**Comment by Jainbrt** [comment]
Thanks Lana. Can we close this issue ?

**Comment by lanak01** [comment]
Yes
