### ISSUE TITLE
create updated csiscaleoperators.csi.ibm.com_cr.yaml sample file with specifics for CNSA

### ISSUE THREAD

**Issue by muenchp1** [IBM/ibm-spectrum-scale-csi#430]
**Describe the bug**
The csiscaleoperators.csi.ibm.com_cr.yaml file that I got from the following command listed in the CNSA 5.1.1.1 Documentation needs updates in regard to the commented out lines for the non-defaults. I can still find 2.1.0 and 5.1.0.3 as example. In addition there should be a sample file for CNSA since the parameter names that customer have to collect in the following list https://www-03preprod.ibm.com/support/knowledgecenter/STXKQY_CNSS_review/spectrum-scale-csi/configure-custom-resource.html do not show up in the sample file, so it is hard to understand where to enter the fields in the cr file.

**To Reproduce**
https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/v2.2.0/operator/config/samples/csiscaleoperators.csi.ibm.com_cr.yaml

**Expected behavior**

Add updated csiscaleoperators.csi.ibm.com_cr.yaml  sample file for CNSA.

**Environment**

CNSA 5.1.1.1

**Comment by deeghuge** [comment]
CSI gets installed with CNSA automatically so this is kind of taken care already
