### ISSUE TITLE
[MDD] Handling images for release

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#44]
The operator needs a better process for targeting images for release with the default images. Today we wait for the quay repos to be created before setting the image, which can lead to some serious release issues.

To fix this I propose the following solution:
1. Default images should be easily changed in a top level playbook, so detailed understanding of the layout  of the operator is not required. 

2. When generating the deployment yaml, a release and dev version should be made  which point  to the  next operator image level and latest nightly respectively.

3. A generated CR should be created from the example CR with links to the nightly, or we should provide a play/script to point to the latest development images.

**Comment by mew2057** [comment]
@whowutwut @dunnevan any thoughts? I wanted to mark this down as more concrete plan.

Basically the way I see the  problem is  we need the operator image to be able to be  promoted to a release. As the  defaults are baked in the build, we need a way to ensure  those are baked in the nightly. The problem, however, is we need to point the images to the nightly for test or users who aren't using  a  release (e.g. contributors).

**Comment by dunnevan** [comment]
Why should the defaults be backed into the build executable?  Could we back them into the build image environment?  Or could we pass them as container args?

**Comment by mew2057** [comment]
We can pass as container args today, we have a defaults in the role dir: 

https://github.com/IBM/ibm-spectrum-scale-csi/blob/96e5ee598544c3fb865355ea3fa23131e2632589/operator/roles/csi-scale/defaults/main.yml#L3

**Comment by mew2057** [comment]
Technically not baked into the executable but the  role.

**Comment by mew2057** [comment]
Closing resolved through environment variables.
