### ISSUE TITLE
The pvc cannot be mounted after changing the gpfs ​​GUI address

### ISSUE THREAD

**Issue by yangxiao1220** [IBM/ibm-spectrum-scale-csi#443]
Hello, first of all thank you for your help, I just started using GPFS, I will describe my problem below and upload my log
- Problem Description
We used the 172.16.101.239 GUI address when we first deployed gpfs csi. In the process of using gpfs, we encountered other problems. After colleagues rebuilt the gpfs system and enabled the GUI on 172.16.101.238, we deleted the operator and CSI and rebuilt to modify the GUI address to 172.16.101.238, but we found that the newly created pvc can be used normally, the old pvc can no longer be used, the following problems encountered when pod is mounted
Error: stat /var/lib/kubelet/pods/98b48ab2-337f-4f2d-b929-dc8eea8f8d25/volumes/kubernetes.io~csi/pvc-55a23ac2-8a9d-4cd9-b771-a115e218e25b/mount: no such file or directory

Can you tell me how to troubleshoot or solve this problem, thank you very much

**Comment by deeghuge** [comment]
Hi @yangxiao1220, Thanks for reaching out. 
You mentioned that gpfs system was rebuilt. Does it mean you had reinstalled the complete gpfs or something else ?
Also if possible please help with the output of 'kubectl describe pv <pvname>' for both working and non working pv along with details about how you are using old pvc for further debugging.

**Comment by deeghuge** [comment]
Closing since no input since long. Please reopen if required
