### ISSUE TITLE
Static pv data not accessible by noobaa endpoint after node reboot

### ISSUE THREAD

**Issue by nehasharma5** [IBM/ibm-spectrum-scale-csi#446]
Environment info
[root@api.ns.cp.fyre.ibm.com ~]# oc version
Client Version: 4.7.13
Server Version: 4.7.13
Kubernetes Version: v1.20.0+df9c838
[root@api.ns.cp.fyre.ibm.com ~]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210719
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@api.ns.cp.fyre.ibm.com ~]#

Actual behavior
Data base corrupted , buckets and its objects are not shown by s3 ls (Bucket name - neha and object : testfile)

Expected behavior
No Database corruption should be done , bucket and its object should be listed by s3 ls

Steps to reproduce
Install noobaa and start a copy object operation into a bucket
Once copy is finished , start another copy operation
While copy operation is going on shutdown the node on which noobaa is installed (I have only endpoint pod scheduled on that node , no other noobaa pode)
Start the node
Delete DB pod
App Node:
[root@fyreauto-x-app1 ~]# s3 ls
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[root@fyreauto-x-app1 ~]# s3 cp testfile s3://neha
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload failed: ./testfile to s3://neha/testfile An error occurred (NoSuchKey) when calling the CreateMultipartUpload operation: The specified key does not exist.
[root@fyreauto-x-app1 ~]# s3 ls
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[root@fyreauto-x-app1 ~]# s3 mb s3://new-buck
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket failed: s3://new-buck An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

Inf node:
[root@api.ns.cp.fyre.ibm.com ~]# oc get pod -o wide
NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE READINESS GATES
noobaa-core-0 1/1 Running 0 73m 10.254.3.167 master1.ns.cp.fyre.ibm.com
noobaa-db-pg-0 1/1 Running 0 60m 10.254.4.17 master0.ns.cp.fyre.ibm.com
noobaa-default-backing-store-noobaa-pod-62daf8d7 0/1 Terminating 0 38m master2.ns.cp.fyre.ibm.com
noobaa-endpoint-565dbbd667-gfzt2 1/1 Running 0 74m 10.254.4.14 master0.ns.cp.fyre.ibm.com
noobaa-operator-6d54447bc5-hr7sb 1/1 Running 1 19h 10.254.3.136 master1.ns.cp.fyre.ibm.com
[root@api.ns.cp.fyre.ibm.com ~]#

Storage cluster
[root@storage-x-master neha]# ls -lrt
total 3
drwxr-x---. 3 2001 2002 4096 Jul 20 04:15 buck-1
drwxr-x---. 3 2001 2002 4096 Jul 22 02:36 my-buck
drwxr-x---. 3 2001 2002 4096 Jul 22 04:26 neha
[root@storage-x-master neha]#

[csi.tar.gz](https://github.com/IBM/ibm-spectrum-scale-csi/files/6899783/csi.tar.gz)

**Comment by nehasharma5** [comment]
@deeghuge As already had detailed discussion regarding this issue. According Noobaa team this something related to CSI. We in our discusssion also concluded this is a CSI issue.

**Comment by madhuthorat** [comment]
Looking at the issue.

**Comment by madhuthorat** [comment]
We would need more debug data to debug the issue, providing a CSI driver image with additional logs to gather debug data.

Please use below image to reproduce the issue and share the logs for the reproduced issue. Thank you.
quay.io/madhuthorat/ibm-spectrum-scale-csi-driver-dev:driver_issue446

To use this image please update the CR for CSI driver and restart the CSI driver to make use of the updated image. Let me know if you need any help with modifying the CR.

**Comment by madhuthorat** [comment]
@nehasharma5 As discussed last week, as this issue is not reproducible with CSI 2.3.0, then can you close this issue ?
Re-open it in the future if you see it again.

**Comment by nehasharma5** [comment]
Yes, as discussed not able to reproduce with CSI 2.30 , in case face again will open a new defect
