### ISSUE TITLE
Can't apply tolerations to snapshotter

### ISSUE THREAD

**Issue by tychristensen** [IBM/ibm-spectrum-scale-csi#448]
**Describe the bug**
When applying tolerations to the CR the snapshotter does not get the toleration I set.
https://github.com/IBM/ibm-spectrum-scale-csi/blob/dev/operator/roles/csiscaleoperator/templates/csi-plugin-snapshotter.yaml.j2

**To Reproduce**
1. Set toleration in CR
2. Describe snapshotter pod to see that the toleration is not set

**Expected behavior**
When I set tolerations in the CR it should be applied to the snapshotter.

**Comment by Jainbrt** [comment]
@tychristensen this is fixed in latest dev image, could you please verify and close the same ?

**Comment by Jainbrt** [comment]
@tychristensen should we close this issue?

**Comment by tychristensen** [comment]
Yes, sorry I forgot to close this last time you commented.
