### ISSUE TITLE
CSI log collection script is broken for CNSA 2.3

### ISSUE THREAD

**Issue by smitaraut** [IBM/ibm-spectrum-scale-csi#462]
**Describe the bug**
The CSI log collection script spectrum-scale-driver-snap.sh is broken for CNSA. It gives the below error although CSI is running-

```
[root@fusion-inf cnsa-ece]# ./spectrum-scale-driver-snap.sh 
No resources found in ibm-spectrum-scale-csi namespace.
ibm-spectrum-scale-csi driver and operator is not running in namespace ibm-spectrum-scale-csi. Please provide a valid namespace
[root@fusion-inf cnsa-ece]# 
```

**To Reproduce**
Download the script from https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/dev/tools/spectrum-scale-driver-snap.sh, make it executable and run

**Expected behavior**
logs should be collected in the output file

**Comment by smitaraut** [comment]
Corresponding CNSA issue- https://github.ibm.com/cloud-native-spectrum-scale/scale-core/issues/2038

**Comment by Jainbrt** [comment]
@smitaraut , it should work witn "-n <namespace>" option such as :

`./spectrum-scale-driver-snap.sh -n ibm-spectrum-scale-ns`

**Comment by deeghuge** [comment]
Since operator name is fixed from CNSA side, this issue is no longer valid.
