### ISSUE TITLE
Some PVCs remain in pending state due to quota mismatch error

### ISSUE THREAD

**Issue by smitaraut** [IBM/ibm-spectrum-scale-csi#463]
**Describe the bug**
2 PVCs created via elasticsearch deployment remained in pending state due to below error-
`Internal desc = Fileset pvc-73e5e86f-c9ea-45b9-b147-942b4b2c2805 present but quota 200001191936 does not match with requested size 200000000000`

While PVCs created via other deployment like mongodb could be bound.

This is with CNSA 2.3 cluster with ECE.

**Comment by smitaraut** [comment]
[csilogs.tar.gz](https://github.com/IBM/ibm-spectrum-scale-csi/files/6987851/csilogs.tar.gz)

**Comment by smitaraut** [comment]
Storageclass used

```
[root@skulks1 csilogs]# oc describe sc ibm-spectrum-fusion-mgmt-sc
Name:                  ibm-spectrum-fusion-mgmt-sc
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           spectrumscale.csi.ibm.com
Parameters:            clusterId=,reclaimPolicy=Delete,volBackendFs=scalerackh
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
[root@skulks1 csilogs]# 

```

**Comment by smitaraut** [comment]
Adding info on root cause to have a trail-

Here pvc size used is 200G which is in terms of 1000
now when quota/size is requested which is not multiple of blocksize(subblock size) then scale does some adjustment and set the quota. This quota check does not happen in first pass when fileset is created but for some reason initial request times out after setquota. Then next retry checks for quota and compare and it fails because 200000000000 (200G) does not match the adjusted quota (200001191936) that is set on the fileset .

**Comment by Jainbrt** [comment]
@smitaraut should we close this issue as this has been fixed ?

**Comment by smitaraut** [comment]
This has been verified and can be closed.
