### ISSUE TITLE
PVC attachment error due to nodemapping issue in CNSA 

### ISSUE THREAD

**Issue by smitaraut** [IBM/ibm-spectrum-scale-csi#465]
**Describe the bug**
CNSA does maps openshift nodes to daemon node names but filesystem GET Rest API returns admin node names which causes the CSI validation for filesystem mount to fail, thus failing the PVC attach operation.

**Expected behavior**
PVC attach should succeed and should be mounted in pod

**Environment**
CNSA 5.1.1.3

**Additional context**
As a tactical solution filesystem mount validation should be skipped

**Comment by smitaraut** [comment]
https://github.ibm.com/cloud-native-spectrum-scale/scale-core/issues/1934

**Comment by Jainbrt** [comment]
@deeghuge should we close this issue?
