### ISSUE TITLE
Implement volume metrics

### ISSUE THREAD

**Issue by bukovjanmic** [IBM/ibm-spectrum-scale-csi#489]
**Is your feature request related to a problem? Please describe.**
It seems the current CSI driver does not implement standard Kubernetes volume metrics / volume stats, e.g. kubelet_volume_stats_used_bytes or kubelet_volume_stats_available_bytes. Therefore, it is not possible to easily monitor e.g. free space on PVCs with Prometheus.

**Describe the solution you'd like**
The CSI driver should expose volume stats so that we can monitor our PVCs (or, if it is already possible, describe this in documentation, as there is nothing on this subject)..

**Describe alternatives you've considered**
Currently the only way to monitor PVCs state is to use workarounds, like create a bash exporter container for each PVC or application, periodically run df command and expose a custom metric via a separate ServiceMonitor.

**Comment by deeghuge** [comment]
Implemented
