### ISSUE TITLE
Snapshotter sidecar and resizer sidecar sometimes run on incorrect nodes after upgrade

### ISSUE THREAD

**Issue by deeghuge** [IBM/ibm-spectrum-scale-csi#504]
We have added snapshotterNodeSelector and resizerNodeSelector in different releases in the CR.
Now when one upgrade csi from version when these feature were not there then snapshot or resizer sidecar can run on node without scale=true label. 

Current Workaround - After upgrade one will need to manually update the CR with snapshotterNodeSelector/resizerNodeSelector

**Comment by madhuthorat** [comment]
What is the proposed fixed idea for this ? We can't update the CR received by the operator code. One fact is Go operator will always used with CSI version >= 2.5.0. So considering this if with Go operator we receive a CR without resizerNodeSelector, then shall we assume in code that we have to run resizer on any node with "scale=true". And log a warning in Go Operator logs stating the resizerNodeSelector is missing in CR ?

**Comment by madhuthorat** [comment]
Any suggestion on the previous question ?

**Comment by madhuthorat** [comment]
Fixed in goop_code branch, PR is raised from same branch at https://github.com/IBM/ibm-spectrum-scale-csi/pull/542

**Comment by Jainbrt** [comment]
This issue is fixed with workaround where new sidecar's nodeselectorlabel will be default set as scale=true.
