### ISSUE TITLE
With the combined repo, we may want  to double check the Issue template

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#51]
With the combined repo, opening this issue to have someone double check the bug template to make sure that we are collecting the correct information, or requesting for the correct information to be  collected.  

This is a nice to have.. but  I suspect the templates should be adjusting anyway... as needed.

**Comment by mew2057** [comment]
We also need tagging automation, I don't want to need to apply tags every time a user makes an issue.

**Comment by mew2057** [comment]
Yeah I think that the templates need to be reworked.

**Comment by deeghuge** [comment]
Closing since we now have issue template. Please reopen if any improvement is still needed in issue template
