### ISSUE TITLE
generate-playbook should install correct version of kustomize

### ISSUE THREAD

**Issue by sam6258** [IBM/ibm-spectrum-scale-csi#530]
**Is your feature request related to a problem? Please describe.**

When running `ansible-playbook tools/ansible/generate-playbook.yaml`, I hit an issue with Travis CI not matching generated files because I had a newer version of kustomize.

**Describe the solution you'd like**

If Travis requires the generator tool to be on the same version of kustomize, then the tool should self-install kustomize to some local directory within the repo clone.

**Describe alternatives you've considered**

I found the correct version of kustomize in the travis log and installed it to a different path than my normal kustomize. I then pointed to that version of kustomize to generate my files. But for someone new to the repo, I had to dig to find this requirement, so we should consider streamlining that tool a bit more.

**Comment by deeghuge** [comment]
Closingas we have plan to move to internal Tekton.
