### ISSUE TITLE
provide versions/build details in logs of operator and driver containers

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#537]
**Is your feature request related to a problem? Please describe.**
We need easy way to validate versions and build of container images. This is required to validate GA builds and open defects.

**Describe the solution you'd like**
1. Provide commitID in images, we should able to query in logs.
2. provide way to query images to determine above info.

**Describe alternatives you've considered**
imageID of containers.
*

**Comment by madhuthorat** [comment]
This will be handled after 2.5.0 considering current deadlines.

**Comment by Jainbrt** [comment]
@deeghuge this should get fix with latest merge for commit id in docker images ?

**Comment by dunnevan** [comment]
No, I just added that piece as a placeholder in the Dockerfile.  I'll open a new PR wiring that up though: #578

We should double check that actually works, also this issue should probably also cover adding revision to generated kustomize and add version in a similar way to be logged.

**Comment by gandhisanjayv** [comment]
validated in 5.1.3 RC2 build
```oc logs ibm-spectrum-scale-csi-t5ssx -c ibm-spectrum-scale-csi|head
I0313 07:00:43.420312       1 main.go:48] Version Info: commit (10b66641e5322b1a44cf7ba7c3023d47d15077d4)```

**Comment by Jainbrt** [comment]
Closing based on Sanjay's validation
