### ISSUE TITLE
Go Operator enhancements (not to be part of baseline code)

### ISSUE THREAD

**Issue by madhuthorat** [IBM/ibm-spectrum-scale-csi#544]
**Is your feature request related to a problem? Please describe.**
Go Operator enhancements (not to be part of baseline code)

**Describe the solution you'd like**
Support for the suggested enhancements mentioned below.

**Describe alternatives you've considered**
These are good to have enhancements. Some may become necessary in future.

**Additional context**
Following enhancements were suggested during code review:
- [x] Use Deployment instead of StatefulSet
- [ ] CR update tasks (webhook)
- [ ] How to enable debug log level for go operator ? default log level. This is enhancement, as unlike Ansible operator sdk, the go operator sdk doesn't support debug logs. For ansible operator, if you set "ANSIBLE_DEBUG_LOGS=true" you would see logs coming from SDK and not from the CSI operator code. Implementing this in CSI Operator would need time.
- [ ] Can we change csi.ibm.com to csi.scale.ibm.com ?
- [x] CRD labels - is it required for cloudpak certification ? can we add it auotmatically via operator sdk  - May be not needed
- [x] Can we create scc as part of operator.yaml instead of creating inside code
- [ ] Remove healthscript - currently which is workaround. This is needed for upgrade path as of now.
- [x] Review the operator service account roles and remove duplicate and remove * rules - This change will need lot of testing.
- [ ] How can we handle csidriver object changes ?
- [x] Need to review duplicate clusterrole rules in operator.yaml
- [x] Secret check is required in the namespace, before creating statefulsets for sidecar containers
- [ ] Making things in sync with cnsa: CA cert, Configmap for images, ImageRegistryMirror etc
- [ ] "/var/lib/kubelet/plugins/spectrumscale.csi.ibm.com/" is not getting cleaned up after driver uninstall

**Comment by deeghuge** [comment]
Closing since most of the items are taken care and others are not in plan
