### ISSUE TITLE
kubectl create the secret fails because the namespace doesn't exist yet.

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-spectrum-scale-csi#55]
**Describe the bug**
I filled in username,  password, and namespace rather than using the environment variable.

When I run kubectl create -f /tmp/csisecret.yaml.  I get an error that the namespace doesn't exist yet.
```
#   kubectl create -f /tmp/csisecret.yaml
Error from server (NotFound): error when creating "/tmp/csisecret.yaml": namespaces "ibm-spectrum-scale-csi-driver" not found
[root@archieprt01 ~] 2020-02-03 15:25:23
```

I think I'm unclear about the instructions.  Do I do the BIG BLUE BUTTON labaled INSTALL first?  Or do I do steps 1, 2, 3 for GUI setup and secret.

It looks like a chicken and egg problem.  I don't have the namespace yet, so I tried doing the steps in the big blue INSTALL button.

**Comment by mew2057** [comment]
You need to INSTALL first, the instructions are intended to be  followed _after_ the operator has been  installed, but before it has been configured.

**Comment by MonicaLemay** [comment]
Thanks John.  I'll close this I understand that I was doing this in the wrong order.

**Comment by MonicaLemay** [comment]
Thanks John. I'll close this I understand that I was doing this in the wrong order.
