### ISSUE TITLE
Enhance generate_static_provisioning_yamls.sh script based on the new volumehandle definition 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#567]
**Is your feature request related to a problem? Please describe.**
Enhance generate_static_provisioning_yamls.sh based on the new volumehandle type for new storageclass 

**Describe the solution you'd like**
Improve generate_static_provisioning_yamls.sh

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by vrushch** [comment]
verified

**Comment by vrushch** [comment]
@Jainbrt please close this defect
