### ISSUE TITLE
Documenation format: There are 2 step ones listed; 1, 2, 1.  It should be 1, 2, 3

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-spectrum-scale-csi#57]
**Describe the bug**
Following the docs in:
https://operatorhub.io/operator/ibm-spectrum-scale-csi-operator

>    1. Ensure the Spectrum Scale GUI is running by pointing your browser to the IP hosting the GUI:
>
>    If you do not see a login follow on screen instructions, or review the GUI Documentation
>
>    2. Create a CsiAdmin group account on in the GUI (currently requires a CLI call):
>
>   export USERNAME="SomeUser"
>   export PASSWORD="SomePassword"
>   /usr/lpp/mmfs/gui/cli/mkuser ${USERNAME} -p ${PASSWORD} -g CsiAdmin
>
>    1. Create a Kubernetes secret for the CsiAdmin user:

**Expected behavior**

>    1. Ensure the Spectrum Scale GUI is running by pointing your browser to the IP hosting the GUI:
>
>    If you do not see a login follow on screen instructions, or review the GUI Documentation
>
>    2. Create a CsiAdmin group account on in the GUI (currently requires a CLI call):
>
>   export USERNAME="SomeUser"
>   export PASSWORD="SomePassword"
>   /usr/lpp/mmfs/gui/cli/mkuser ${USERNAME} -p ${PASSWORD} -g CsiAdmin
>
>   3.  Create a Kubernetes secret for the CsiAdmin user:

**Comment by mew2057** [comment]
<img width="1082" alt="Screen Shot 2020-02-21 at 11 28 47 AM" src="https://user-images.githubusercontent.com/1195452/75052310-60de4700-549d-11ea-88cd-c914d7d9dab5.png">

This should be  resolved in  `1.1.0`
