### ISSUE TITLE
The spacing in the sample /tmp/csisecret.yaml is incorrect for password and username

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-spectrum-scale-csi#58]
**Describe the bug**
I am using instructions in 
https://operatorhub.io/operator/ibm-spectrum-scale-csi-operator

The sample /tmp/csisecret.yaml has the wrong spacing for password and username.  This is what is on the website.
```
cat << EOF > /tmp/csisecret.yaml
  apiVersion: v1
  data:
    password: ${PASSWORD_B64}
    username: ${USERNAME_B64}
  kind: Secret
  type: Opaque
  metadata:
    name: csisecret    # This should be in your CSIScaleOperator definition
    namespace: ${OPERATOR_NAMESPACE} 
    labels:
      app.kubernetes.io/name: ibm-spectrum-scale-csi-operator # Used by the operator to detect changes, set on load of CR change if secret matches name in CR and namespace.
  EOF
```
I had to change it to:
```
cat << EOF > /tmp/csisecret.yaml
  apiVersion: v1
  data:
        password: UGFzc3cwcmQK
        username: Y3NpYWRtaW4K
  kind: Secret
  type: Opaque
  metadata:
    name: csisecret    # This should be in your CSIScaleOperator definition
    namespace: ${OPERATOR_NAMESPACE} 
    labels:
      app.kubernetes.io/name: ibm-spectrum-scale-csi-operator # Used by the operator to detect changes, set on load of CR change if secret matches name in CR and namespace.
  EOF 
```
**To Reproduce**
Follow the steps in the Spectrum Scale GUI setup

# Deployment
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mew2057** [comment]
I think both of  these are identical as far as YAML is concerned.  I think this is directly related to Issue #56 .

**Comment by smitaraut** [comment]
Who would use instructions from https://operatorhub.io/operator/ibm-spectrum-scale-csi-operator? Only an OLM user, right? So we should also give instructions to create secret using OLM, why mix CLI and GUI.

Please refer to this video on how to create GUI secret using OLM-
https://www.youtube.com/watch?v=xZhlhF41FcM

**Comment by MonicaLemay** [comment]
It is correct that only an OLM user will use the instructions on https://operatorhub.io/operator/ibm-spectrum-scale-csi-operator.   I don't understand what Smita is saying with "e should also give instructions to create secret using OLM,"?   Smity did  you mean to say OCP?  I watched the video and it is geared to OCP.  If that is the case then, yes, we should give instructions on both CLI and OCP GUI.

**Comment by smitaraut** [comment]
Yes I meant OCP GUI instead of OLM. But I get your point that this can also be referred to by CLI users.
