### ISSUE TITLE
Should pre-reqs (OS, Spectrum scale, docker,kubernetes) versions be listed somewhere.

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-spectrum-scale-csi#59]
Using the documentation in https://operatorhub.io/operator/ibm-spectrum-scale-csi-operator

I was wondering if  rpm pre-reqs (OS, Spectrum scale, docker,kubernetes) versions be listed somewhere.   Currently I am running with 

```
Spectrum Scale 5.0.4.1
Red Hat 7.6
kubeadm-1.15.2-0.x86_64
kubernetes-cni-0.7.5-0.x86_64
kubelet-1.15.2-0.x86_64
kubectl-1.15.2-0.x86_64
docker-ce-18.06.1.ce-3.el7.x86_64
```

I'm having numerous problems with the instructions and wondering if this could be caused by not having the right versions.

**Comment by mew2057** [comment]
Are you having problems outside of the already opened issues? None of the opened issues should be  with  the version.

**Comment by MonicaLemay** [comment]
Thanks John.  I'm glad that I'm using supported versions.  However, shouldn't there be a statement somewhere about minimum levels of k8's, docker, rhel and Spectrum Scale?

**Comment by mew2057** [comment]
There should be at some point for k8s, and Spectrum Scale. I don't _think_ we're as concerned about  docker version and definitely we  don't care about the rhel version.

I think the requirements are largely an exercise for the driver over the  operator.

**Comment by MonicaLemay** [comment]
Thanks John.  I"m not having any issues other than the ones that I opened.  I can close this.
