### ISSUE TITLE
Set default pool to first data pool for tiering

### ISSUE THREAD

**Issue by drolsonibm** [IBM/ibm-spectrum-scale-csi#594]
## Describe the bug
Currently, the default storage pool is set to system, but to behave similar to the standard policy file if there are any data pools other than system those should be the default. 

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. Have a storage system with multiple pools, some of which allow for dataOnly or dataAndMetadata.
2. List the policy file and the default SET POOL rule for CSI will be system instead of the expected pool

## Expected behavior
The default pool for file placement on files that don't match any SET POOL rules should default to the first data pool.

**Comment by Jainbrt** [comment]
@drolsonibm could you please verify and close this?

**Comment by drolsonibm** [comment]
I had verified this a while back so I am going to close out. I had verified that it worked with system pool as the only pool, and a few data pools and the first one maintained it's ordering from the gui request and set it appropriately.
