### ISSUE TITLE
Unclear error message for minimum version requirement not met for tier option.

### ISSUE THREAD

**Issue by vrushch** [IBM/ibm-spectrum-scale-csi#608]
When minimum version requirement is not met for tier, Error message is 

> failed to provision volume with StorageClass sc-friendly-bats-950": rpc error: code = FailedPrecondition desc = the minimum required Spectrum Scale Filesystem version for tiering support with CSI is 5.1.3-0

we can add more clarification by changing it to

> failed to provision volume with StorageClass sc-friendly-bats-950": rpc error: code = FailedPrecondition desc = for tiering support with CSI, the minimum required Spectrum Scale Filesystem version is 27.00 (5.1.3.0)

**Comment by madhuthorat** [comment]
@drolsonibm Please check this issue.

**Comment by drolsonibm** [comment]
I 100% agree we should add in the fs version of 27.00. 
```
the minimum required Spectrum Scale Filesystem version for tiering support with CSI is 27.00 (5.1.3-0)
```

The current message is consistent with other version checks. I can change the formatting of the message but want to get approval from @deeghuge or @madhuthorat first in case there was a specific format for a reason.  If agreed, I will change to your suggestion above.
Some other examples for message formatting just for reference:
```
driver/csiplugin/controllerserver.go:			return nil, status.Error(codes.Internal, "the minimum required Spectrum Scale version for permissions support with CSI is 5.1.1-2")
driver/csiplugin/controllerserver.go:		return status.Error(codes.FailedPrecondition, "the minimum required Spectrum Scale version for snapshot support with CSI is 5.1.1-0")
driver/csiplugin/controllerserver.go:		return status.Error(codes.FailedPrecondition, "the minimum required Spectrum Scale version for volume cloning support with CSI is 5.1.2-1")
driver/csiplugin/controllerserver.go:		return status.Error(codes.FailedPrecondition, "the minimum required Spectrum Scale Filesystem version for tiering support with CSI is 5.1.3-0")
```

**Comment by vrushch** [comment]
verified
