### ISSUE TITLE
Independent Fileset is not getting deleted, on deleting the snapshot pvc first and snapshot later.

### ISSUE THREAD

**Issue by monimeht** [IBM/ibm-spectrum-scale-csi#620]
##Bug Description
Independent Fileset is not getting deleted, on deleting the snapshot pvc first and snapshot later.

## How to Reproduce?
1. Create SC with version = 2.
2. Create PVC using the using the new storage class.
3. Create SnapshotClass with window =15 mins.
4. Create Snapshots of the above PVCs.
5. Delete all the Snapshots created, and leave the one snapshot.
6. Delete the PVC.
7. Delete the snapshot.

## Expected behavior
The independent fileset should get deleted.

### Data Collection and Debugging

Environmental output

All the Snippets are attached.

**Comment by monimeht** [comment]
Image Used :
quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator:dev
name: CSI_DRIVER_IMAGE
          value: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:dev

**Comment by madhuthorat** [comment]
@monimeht Please verify this and let me know if the fix works.

**Comment by Jainbrt** [comment]
Issue is reproduced on Monica's cluster,she should be updating the defect soon.

**Comment by monimeht** [comment]
Verified the issue. Working fine.
