### ISSUE TITLE
Add ibm-entitlement-key as default pull secret 

### ISSUE THREAD

**Issue by deeghuge** [IBM/ibm-spectrum-scale-csi#632]
## Describe the bug
Add `ibm-entitlement-key` as default pull secret for CSI driver.

https://playbook.cloudpaklab.ibm.com/cm/ibmEntitlementKeyPullSecret

Additionally try if we can implement this 
For any CustomResource (CR) with a Pod that pulls from the entitled registry, the owning Operator MUST check for pull failures and include a message to the user for debug
## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. ...

### Data Collection and Debugging

Environmental output

- What openshift/kubernetes version are you running, and the architecture? 
- `kubectl get pods -o wide -n < csi driver namespace> `
- `kubectl get nodes -o wide`
- CNSA/Spectrum Scale version 
- Remote Spectrum Scale version 
- Output for `./tools/spectrum-scale-driver-snap.sh -n < csi driver namespace> -v `

Tool to collect the CSI snap:

`./tools/spectrum-scale-driver-snap.sh -n < csi driver namespace>`

### Add labels

- Component:
- Severity:
- Customer Impact:
- Customer Probability:
- Phase:

Note : See [labels](https://github.com/IBM/ibm-spectrum-scale-csi/labels) for the labels

**Comment by Jainbrt** [comment]
Verified
