### ISSUE TITLE
Snapshots getting created even on giving incorrect parameter in Snapshot Class.

### ISSUE THREAD

**Issue by monimeht** [IBM/ibm-spectrum-scale-csi#642]
## Describe the bug
Snapshots getting created, on giving incorrect parameter in Snapshot Class.

## How to Reproduce?

1. Create Storageclass with version = 2.
2. Create PVC.
3. Create snapshotclass with incorrect parameter like snapwindow1, snawindowtest .
4. Create volumesnapshot.
[snapparam.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/8138855/snapparam.txt)

### Data Collection and Debugging

Environmental output

- What openshift/kubernetes version are you running, and the architecture? 
- `kubectl get pods -o wide -n < csi driver namespace> `
- `kubectl get nodes -o wide`
- CNSA/Spectrum Scale version 
- Remote Spectrum Scale version 
- Output for `./tools/spectrum-scale-driver-snap.sh -n < csi driver namespace> -v `

Tool to collect the CSI snap:

`./tools/spectrum-scale-driver-snap.sh -n < csi driver namespace>`

### Add labels

- Component:
- Severity:
- Customer Impact:
- Customer Probability:
- Phase:

Note : See [labels](https://github.com/IBM/ibm-spectrum-scale-csi/labels) for the labels

**Comment by monimeht** [comment]
Snapshots are still getting created even on giving incorrect parameter in Snapshot Class like snapWindow1.
Find attached the steps and yaml used.

Setup Details:
[root@monica-multi-master yaml]# oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.7.0     True

[root@monica-multi-worker-1 ~]# /usr/lpp/mmfs/bin/mmdiag
Current GPFS build: "5.1.5.0 220713.105046".
Built on Jul 13 2022 at 14:42:19

[root@monica-multi-master yaml]# kubelet --version
Kubernetes v1.23.4

[bug642.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/9615500/bug642.txt)

**Comment by monimeht** [comment]
Verified this issue on CSI280 build and found that Snapshots are getting created even on giving incorrect parameter in Snapshot Class.

Followed the below steps:
Create Storageclass with version = 2.
Create PVC.
Create snapshotclass with incorrect parameter like snapwindow1, snawindowtest .
Create volumesnapshot.

The volumesnapshot gets created successfully without any error.

**Comment by monimeht** [comment]
[issue642.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/10040061/issue642.txt)

**Comment by monimeht** [comment]
[issue642.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/10040242/issue642.txt)

**Comment by monimeht** [comment]
[issue642.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/10040554/issue642.txt)

**Comment by Jainbrt** [comment]
@amdabhad could you please plan this defect fix ?

**Comment by deeghuge** [comment]
We are not planning to add any strict check for unknown param in snapshotClass
