### ISSUE TITLE
Check to change verb from '*' to 'get'

### ISSUE THREAD

**Issue by madhuthorat** [IBM/ibm-spectrum-scale-csi#662]
## Describe the bug
Check to change verb from '*' to 'get' - in [operator/config/rbac/role.yaml] - check comment - https://github.com/IBM/ibm-spectrum-scale-csi/pull/644/files/96b040976d739079b12010916a7996507d4d179a#diff-bf75d41206005954349fa60826c9cc3bd1a976c9e5c8884de0cb59ee68a13fa8
  resources:
  - clusterversions
  verbs:
  - '*'
  
## Expected behavior
Check to change verb from '*' to 'get'

**Comment by nitishkumar4** [comment]
@Vrushal PR is merged, please validate if the issue is fixed.

**Comment by madhuthorat** [comment]
Closing as fixed.
