### ISSUE TITLE
Remove the dependeny for hostNetwork: true in driver pods 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#663]
## Describe the bug
Remove the dependency for hostNetwork: true in driver pods 

## How to Reproduce?
Remove the dependency for hostNetwork: true in driver pods 

## Expected behavior
Remove the dependency for hostNetwork: true in driver pods

**Comment by deeghuge** [comment]
Consolidating under one issue. Duplicate of #457
