### ISSUE TITLE
mmxcp compression copy script validation

### ISSUE THREAD

**Issue by madhuthorat** [IBM/ibm-spectrum-scale-csi#667]
## Describe the bug
Validate script from Dan as mentioned in below email:
==============================================
I've created a test version of xcputil.sh for you and your team to checkout.  It is hardcoded to copy the compression attribute from the source files to the target files.

I'm interested to see if it functions well for you, and especially if you notice any performance degradation.

Dan

To: Deepak 
From: April Date: 02/25/2022 01:52PM
Subject: mmxcp compression copy

 Hi Deepak,

I opened User Story 291948 https://jazz07.rchland.ibm.com:21443/jazz/web/projects/GPFS#action=com.ibm.team.workitem.viewWorkItem&id=291948
to track the CSI request for mmxcp to compress the files after the copy.

Can you please confirm that you want us to switch directions and implement this user story for 5.1.4 ? That will be the only story we can deliver 
(hopefully after design has been done) for the 2Q release.  If the design turns out to be really complex then it will go into 5.1.5 and nothing else
will be delivered for 5.1.4. 

We should also work with you on the use case requirements so that we get a complete and accurate design.

- New external to indicate that compressed files in --source will be re-compressed in --target.  Default is no.
- Each file needs to be determined whether it is compressed or not, and only those that are will be re-compressed in --target.  Other option is to just 
compress all of the files in --target after copy.  The all file option is probably easier to implement and less performance hit.  we could have a switch on the 
external to indicate which kind and implement it in stages.  ??
- Performance will be an issue and customers are willing to trade off time for mmxcp command to run for the function.
- Would customer accept certain files not being compressed in the first implementation - I know there was some discussion on sparse files. 

Please let us know what else - Thanks for your input.  

April L. Brown
Spectrum Scale Test
DPE Scrum
[brownap@us.ibm.com](mailto:brownap@us.ibm.com)
(845) 433 - 8173, (T/L) 293 - 8173

============================================

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

### Data Collection and Debugging

Environmental output

## Additional context

Note : See [labels](https://github.com/IBM/ibm-spectrum-scale-csi/labels) for the labels

**Comment by deeghuge** [comment]
Currently no plan to work on this part. Will reopen if required
