### ISSUE TITLE
The namespaces slightly different my-ibm-spectrum-scale-csi-operator vs. ibm-spectrum-scale-csi-driver

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-spectrum-scale-csi#68]
In the big blue button install instructions for the framework, the namespaces that get created are as follows:
```
# kubectl get ns | grep csi
my-ibm-spectrum-scale-csi-operator   Active   2d18h
```
Then when I follow instructions in creating the secret, the suggested namespace is:

    Create a Kubernetes secret for the CsiAdmin user:
      export USERNAME_B64=$(echo $USERNAME | base64)
      export PASSWORD_B64=$(echo $PASSWORD | base64)
      export OPERATOR_NAMESPACE="ibm-spectrum-scale-csi-driver"  # Set this to the namespace you deploy the operator in.

The `ibm-spectrum-scale-csi-driver` ns doesn't exist.  The big blue button INSTALL instructions did  not create it.

**Comment by mew2057** [comment]
It looks like this one is one  operatorHub. We generally recommend for installation `ibm-spectrum-scale-csi-driver` we do call out that the `OPERATOR_NAMESPACE` should  be set to your namespace. I'm not sure what the best practice for this is any thoughts @whowutwut in terms of  improving documentation?

**Comment by whowutwut** [comment]
For the users and password in our doc, we put , we have the following:

```
export USERNAME="SomeUser"
export PASSWORD="SomePassword"
```


I'll create  a PR to also do the same thing for the OPERATOR_NAMESPACE. 

```
export OPERATOR_NAMESPACE="SomeNamespace"
```
