### ISSUE TITLE
Upgrade operator-sdk and golang to the latest version

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#694]
**Is your feature request related to a problem? Please describe.**
Upgrade operator-sdk to 1.24.0

**Describe the solution you'd like**
Upgrade operator-sdk to 1.24.0

**Comment by amdabhad** [comment]
Hi @nitishkumar4 , please update the operator-sdk and golang version to latest.
TODO:
1. Update the operator-sdk and goland version to latest.
2. Document the process for operator-sdk and golang version update
3. Document how both the updates impact CSI code and what changes are required

**Comment by nitishkumar4** [comment]
## Go Installation

### Using Yum utility

        $ yum install golang
        Note: This may not install latest  or any specific version of golang.

### Using tar package file(Recommended)

1. Download the required package:

       wget https://go.dev/dl/go1.18.4.linux-amd64.tar.gz
       tar -xzf go1.18.4.linux-amd64.tar.gz 
       rm -rf /usr/local/go
       cp -r go /usr/local 
       cp -r go/bin/go /usr/bin/go <--- WSL

2. Create environment variables:

       export GOROOT=/usr/local/go 
       export GOPATH=$HOME/
       export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

3. Update bash file:

       $ vim ~/.bash_profile
       Note: Add the above environment variables in this file as well, to retain the environment variables across different sessions.
       For Ubuntu(WSL)
       $ vim ~/.profile

4. Verify installation:

       go version
       go env

**Comment by nitishkumar4** [comment]
## Installation Of Operator SDK Latest

        export ARCH=$(case $(arch) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(arch) ;; esac)
        export OS=$(uname | awk '{print tolower($0)}')
        export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/latest/download
        curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
        gpg --keyserver keyserver.ubuntu.com --recv-keys 052996E2A20B5C7E
        curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt
        curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt.asc
        gpg -u "Operator SDK (release) <cncf-operator-sdk@cncf.io>" --verify checksums.txt.asc
        grep operator-sdk_${OS}_${ARCH} checksums.txt | sha256sum -c -
        chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk
        operator-sdk version

**Comment by nitishkumar4** [comment]
#### Update Base OS of Operator Image:

File: operator\build\Dockerfile
FROM --platform=$BUILDPLATFORM golang:1.18 as builder


#### Update Base OS of Driver Image:

File:   driver\build\Dockerfile
FROM --platform=$BUILDPLATFORM golang:1.18 AS builder
