### ISSUE TITLE
Document the Image-Digest in the Documentation Section - Deployment Consideration 

### ISSUE THREAD

**Issue by ps20renar** [IBM/ibm-spectrum-scale-csi#714]
Currently in the new 2.5.1 Documentation we don't found the image pull digest for the Version 2.5.1.
Here ist what currently found:For IBM Spectrum Scale Container Storage Interface driver 2.5.1:
quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v2.5.1
quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator:v2.5.1
us.gcr.io/k8s-artifacts-prod/sig-storage/csi-resizer:v1.3.0
us.gcr.io/k8s-artifacts-prod/sig-storage/csi-snapshotter:v5.0.1
us.gcr.io/k8s-artifacts-prod/sig-storage/csi-attacher:v3.4.0
us.gcr.io/k8s-artifacts-prod/sig-storage/livenessprobe:v2.6.0
us.gcr.io/k8s-artifacts-prod/sig-storage/csi-node-driver-registrar:v2.4.0
us.gcr.io/k8s-artifacts-prod/sig-storage/csi-provisioner:v3.1.0

Because of our image pull secret in an air gap environment we use to load this over our current Nexus proxy registry. 
Please add the imagelist with digests also in the documentation. So we can verify if some one are wrong during update.
Regards Renar

**Comment by deeghuge** [comment]
Hi @ps20renar We started documenting the sha in the kc. 
https://www.ibm.com/docs/en/spectrum-scale-csi?topic=planning-deployment-considerations

**Comment by deeghuge** [comment]
@Jainbrt , Please work with Teja to add sha details in 2.5 documentation like we added in 2.6.0

**Comment by deeghuge** [comment]
It is taken care
