### ISSUE TITLE
CSI 2.6.0 Knowledge Center Errors

### ISSUE THREAD

**Issue by tristan-le** [IBM/ibm-spectrum-scale-csi#723]
**Description**
CSI Knowledge Center Installation Steps Error (https://ibmdocs-test.mybluemix.net/docs/en/Scale_CSI_test?topic=installation-installing-spectrum-scale-container-storage-interface-driver-using-clis)

For Step 2 in "Phase 1: Deploying the Operator", there are mentions of CSI 2.5.0 and CSI 2.5.1, when it should be CSI 2.6.0

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/66130947/169398057-b714135d-bfe0-450d-81ed-34ad530c51ab.png">

**Comment by amdabhad** [comment]
@tristan-le  2.6.0 doc is still work in progress, and this is fixed by Teja today. You may see the same content due to caching by browser, if you still see the same content, you can check this in another browser or in incognito mode. Thanks!
