### ISSUE TITLE
OLM install is not working on CSI 2.6.0

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#729]
## Describe the bug
OLM install is not working on CSI 2.6.0

## How to Reproduce?
1. Install CSI using CSI 2.6.0

## Expected behavior
CSI driver should be installed using OLM

**Comment by nitishkumar4** [comment]
Findings:
CSI can be deployed in 3 types of enviroment:
- Vanilla Kubernetes
- OCP: CNSA(operator) + CSI
- OCP: CNSA  + CSI

For Vanilla Kubernetes, SecurityContextConstraints is not required.
For OCP: CNSA(operator) + CSI, CNSA operator.yaml file takes care of installing SecurityContextConstraints.
For OCP:  without CNSA operator: 
Following error is observed:
```
  Warning  FailedCreate  5s (x14 over 46s)  replicaset-controller  Error creating: pods "ibm-spectrum-scale-csi-provisioner-776d78f649-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "ibm-spectrum-scale-privileged": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

**Comment by nitishkumar4** [comment]
Few updates:

For installing CSI using OLM in OCP cluster, user needs to create securitycontextconstraint manually. Documentation needs to be updated for the same. Conveyed the same to Teja.

Page: Performing pre-installation tasks

If installing CSI 2.6.0 using OLM, on a Redhat Openshift Cluster Platform, create securitycontextconstraint in the cluster.
Securitycontextconstraint will ensure that driver and controller pods have sufficient access privileges.

- Issue the following command to download the securitycontextconstraint manifest for CSI 2.6.0

```sh
curl -O https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/v2.6.0/operator/config/overlays/cnsa/security_context_constraint.yaml
```
- Issue the following command to apply the securitycontextconstraint manifest to create `spectrum-scale-csiaccess` security_context_constraint.

```sh
kubectl create -f security_context_constraint.yaml
```

**Comment by deeghuge** [comment]
@Jainbrt can this be closed ?
