### ISSUE TITLE
Documentation: Update CSI 2.5.0 and 2.6.0 web documentation Troubleshooting section.

### ISSUE THREAD

**Issue by nitishkumar4** [IBM/ibm-spectrum-scale-csi#764]
## Describe the bug

Following error is observed when applying operator manifest file for CSI v2.5.0+
```
Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "csiscaleoperators.csi.ibm.com", Namespace: ""
for: "ibm-spectrum-scale-csi-operator.yaml": CustomResourceDefinition.apiextensions.k8s.io "csiscaleoperators.csi.ibm.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
```

## How to Reproduce?
1. Try upgrading CSI from version prior to 2.2.0 till 2.5.0, while applying operator manifest file for 2.5.0 or more, applying manifest will fail with above mentioned error. 

## Expected behavior
Operator manifest file should get applied in the cluster without any error. The fix for this error should be available under
Troubleshooting section of CSI web documentation for version 2.5.0+

**Comment by amdabhad** [comment]
We have a RTC issue - https://jazz07.rchland.ibm.com:21443/jazz/web/projects/GPFS#action=com.ibm.team.workitem.viewWorkItem&id=299701 opened for this, so closing this one.
