### ISSUE TITLE
Add IBM Spectrum Scale CSI provisioner to Storage Class list

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#77]
On Openshift 4 I cannot create IBM CSI storage classes on web console. The problem can be seen if you go to Storage -> Storage Classes. Click there on 'Create Storage Class', now on the list of available provisioner you cannot find `spectrumscale.csi.ibm.com` which means I can only create it via CLI. 

Please add `spectrumscale.csi.ibm.com` to the list of available provisioner on Openshift 4.

**Comment by deeghuge** [comment]
You can try following to create the StorageClass from web console. 
Storage -> Storage Classes -> edit YAML -> Enter the storageClass details in YAML format.

**Comment by przem123** [comment]
I would like to create multiple storage classes in the UI only.  Editing yaml would be too time consuming. Please add the provisioner to the list.

**Comment by deeghuge** [comment]
>> Please add spectrumscale.csi.ibm.com to the list of available provisioner on Openshift 4.

When CSI driver is installed on openshift, spectrumscale.csi.ibm.com get listed as part of available provisioner. No further improvement planned hence closing

![image](https://user-images.githubusercontent.com/27725248/154483601-0de0a563-24cf-483e-9004-698c30a32b6d.png)
