### ISSUE TITLE
CSI pods goes into crashloopback state, on giving primary gui node as invalid in CR. 

### ISSUE THREAD

**Issue by monimeht** [IBM/ibm-spectrum-scale-csi#780]
## Describe the bug
CSI pods goes into crashloopback state, on giving primary gui node as invalid and secondary gui node as valid nodes CR. 

## How to Reproduce?

1. Update primary gui node as invalid and secondary as Valid entry in CR.
```
#      cacert:  "spectrumscale-trusted-ca"
      restApi:
        - guiHost: "monica-multi-scalegui-21.fyre.ibm.com"
        - guiHost: "monica-multi-scalegui-2.fyre.ibm.com"
#        - guiHost: "monica-multi-scalegui-3.fyre.ibm.com"
```
2. Apply the CR.
3. Observe the csi pods.

## Expected behavior
On applying the CR, the valid gui node should start working, also the pods should not get into crashloopback state.

### Data Collection and Debugging

Environmental output

[root@monica-multi-master ~]# kubectl get pods
```
NAME                                                  READY   STATUS             RESTARTS         AGE
ibm-spectrum-scale-csi-attacher-5f6cb77946-f2vcb      0/1     CrashLoopBackOff   37 (3m15s ago)   23h
ibm-spectrum-scale-csi-attacher-5f6cb77946-ksbbt      0/1     CrashLoopBackOff   47 (35s ago)     23h
ibm-spectrum-scale-csi-nj8hv                          2/3     CrashLoopBackOff   23 (2m42s ago)   95m
ibm-spectrum-scale-csi-operator-7489c74f45-hrfqr      1/1     Running            782 (2d6h ago)   20d
ibm-spectrum-scale-csi-provisioner-6d55c779bb-4pntc   1/1     Running            46 (5m15s ago)   23h
ibm-spectrum-scale-csi-resizer-8496f8d6bb-t6g8x       0/1     CrashLoopBackOff   47 (75s ago)     23h
ibm-spectrum-scale-csi-rmmbp                          2/3     CrashLoopBackOff   28 (3m35s ago)   121m
ibm-spectrum-scale-csi-snapshotter-777b9655f9-65jw9   0/1     CrashLoopBackOff   37 (3m35s ago)   23h

```
`
```
[root@monica-multi-master ~]# oc describe pod ibm-spectrum-scale-csi-attacher-5f6cb77946-f2vcb
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  32m (x45 over 152m)     kubelet  Liveness probe failed: Get "http://10.244.2.26:8080/healthz/leader-election": dial tcp 10.244.2.26:8080: connect: connection refused
  Warning  BackOff    2m44s (x637 over 151m)  kubelet  Back-off restarting failed container
```

```
[root@monica-multi-master ~]# kubectl describe pod ibm-spectrum-scale-csi-nj8hv
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Warning  BackOff  4m15s (x721 over 154m)  kubelet  Back-off restarting failed container
```

[attacherlogs.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/9374011/attacherlogs.txt)
[driverpodlogs.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/9374012/driverpodlogs.txt)
[driverpodlogs2.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/9374013/driverpodlogs2.txt)
[provisionerlogs.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/9374014/provisionerlogs.txt)

FIND attached the pod logs.

### Add labels

- Component:
- Severity:
- Customer Impact:
- Customer Probability:
- Phase:

Note : See [labels](https://github.com/IBM/ibm-spectrum-scale-csi/labels) for the labels

**Comment by amdabhad** [comment]
Fixed in quay.io/amdabhad/csi-driver-gui-ha:300822

**Comment by monimeht** [comment]
Verified the issue and it is working fine. 
On giving incorrect primary gui host, the pods are not moving to crashloopback.

Find attached the logs and setup details:
[root@monica-multi-master ~]# oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.7.0     True

[logs1.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/9615912/logs1.txt)
[logs2.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/9615914/logs2.txt)
