### ISSUE TITLE
[CSI 2.6.0] Documentation enhancement for fsGroup feature- only applicable to RWO volumes

### ISSUE THREAD

**Issue by israel-a-vizcarra** [IBM/ibm-spectrum-scale-csi#793]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Summary of changes for CSI 2.6.0 need to clearly state that fsGroup feature is only applicable for RWO volumes

**Additional context**

https://www.ibm.com/docs/en/spectrum-scale-csi?topic=26-summary-changes

![image](https://user-images.githubusercontent.com/113067770/188989048-16b2f6d1-35e6-4fa8-b4fd-be4c7ff89454.png)

**Comment by amdabhad** [comment]
This is updated in 2.6 docs.
