### ISSUE TITLE
Don't use IsNotMountPoint 

### ISSUE THREAD

**Issue by sam6258** [IBM/ibm-spectrum-scale-csi#799]
`IsNotMountPoint` is deprecated. Consider switching to `IsMountPoint`.

https://github.com/IBM/ibm-spectrum-scale-csi/blob/ab135e7569c9dc2bd51ff506379e18090c27a632/driver/csiplugin/nodeserver.go#L107

**Comment by amdabhad** [comment]
Fixed by https://github.com/IBM/ibm-spectrum-scale-csi/pull/825
