### ISSUE TITLE
[MDD] Power and Z support for the operator

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#8]
# Power and Z support for the operator

## Dependencies
* [Operator SDK](https://github.com/operator-framework/operator-sdk)

## Description

The Spectrum Scale CSI Operator has a  requirement to support both the `s390x` and `ppc64le` architectures.

## Problem
Testing  on an `s390x` system revealed a gap in the `operator-sdk`, today `s390x` is not in  the support matrix for the  `operator-sdk` tool or the ansible operator. I _don't_ think this applies to `ppc64le`, as [binaries exist](operator-sdk-v0.14.1-ppc64le-linux-gnu).

For now I have a fix that I rolled by hand in PR #7, using a custom [operator-sdk build]( https://github.com/mew2057/operator-sdk/tree/ansible-z) for s390x. I'm currently  hosting the s390x  build of the image on  [quay](https://quay.io/repository/mew2057/ansible-operator?tab=tags).

## Resolution
The path to resolution is likely going  to require some form of upstream contribution to the `operator-sdk` upstream repository,  as I don't currently see a support timeline.

**Comment by mew2057** [comment]
Power has literally all of the same issues. `tini` and `inotify` need  to be changed for power:

https://github.com/mew2057/operator-sdk/tree/ansible-p
https://quay.io/repository/mew2057/ansible-operator?tab=tags

once that's rebuilt the operator just works when we change the  base image.

**Comment by mew2057** [comment]
Slipped past the 1.1.0 release.

**Comment by thuyanhnguyen** [comment]
@mew2057 would you please instruct how to use Operator-sdk in s390x?

**Comment by mew2057** [comment]
Image: 
https://quay.io/repository/operator-framework/ansible-operator-s390x

For building the  operator-sdk binary (on s390x): 
https://github.com/operator-framework/operator-sdk/tree/master/doc/dev

**Comment by deeghuge** [comment]
@mew2057, Since we moved to ansible-operator:v0.16.0 and we have operator image available for all architecture, can we close this issue now?
