### ISSUE TITLE
df -hT shows gpfs filesystem size instead of available size

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#80]
I assigned 1GB dynamic storage to my mongo DB pod. Unfortunately, I can see with `df -hT` 15T size instead of 1GB for my mount point. 
```
sh-4.2$ df -hT
Filesystem             Type     Size  Used Avail Use% Mounted on
overlay                overlay  200G   44G  157G  22% /
tmpfs                  tmpfs     64M     0   64M   0% /dev
tmpfs                  tmpfs     63G     0   63G   0% /sys/fs/cgroup
shm                    tmpfs     64M     0   64M   0% /dev/shm
tmpfs                  tmpfs     63G  4.1G   59G   7% /etc/passwd
/dev/mapper/sr650-root xfs      200G   44G  157G  22% /etc/hosts
remote_fs0_1m          gpfs      15T   61G   15T   1% /var/lib/mongodb/data
tmpfs                  tmpfs     63G   24K   63G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                  tmpfs     63G     0   63G   0% /proc/acpi
tmpfs                  tmpfs     63G     0   63G   0% /proc/scsi
tmpfs                  tmpfs     63G     0   63G   0% /sys/firmware
```

Can you fix the output ?

**Comment by deeghuge** [comment]
Please try setting --filesetdf on filesystem. After this container will report correct size. 
mmchfs <Filesystem name> --filesetdf

Note : This only works for fileset based volumes.

**Comment by przem123** [comment]
The storage I have is dynamically provisioned. Can you automatically enable the --filesetdf option with the CSI driver?

**Comment by deeghuge** [comment]
Currently filesystems are created and configured before deploying CSI Driver. In future release we will try to get this into features if possible.

**Comment by deeghuge** [comment]
This is documented as prerequisite for deploying CSI. If this needs to be done then CNSA is the right place for it where we create new filesystem.  Closing it for CSI side
