### ISSUE TITLE
resolve linting issues in the code 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#817]
## Describe the bug
resolve linting issues in the code 

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. Run any known linter to find and resolve the linting issue in the code 

## Expected behavior
resolve linting issues in the code

**Comment by amdabhad** [comment]
Linter issues are fixed by PR https://github.com/IBM/ibm-spectrum-scale-csi/pull/974
