### ISSUE TITLE
Support allowVolumeExpansion option for storage classes

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#82]
Storage Classes have option `allowVolumeExpansion: true` which enables resizing of existing PVCs. Currectly, the CSI driver ignores the param, so that it is not possible to change size of an existing PVC connected to a specific app.

Please add this functionality. Consider using one of the existing GUI rest call (POST quota) for changing GPFS quota.

**Comment by deeghuge** [comment]
Since the volume expansion feature is still in Beta in k8s we can not support it. 
This is in our todo list but it should be GA'ed first.

**Comment by deeghuge** [comment]
The Volume expansion feature is now GA'ed.

**Comment by deeghuge** [comment]
> Since the volume expansion feature is still in Beta in k8s we can not support it.
> This is in our todo list but it should be GA'ed first.

The Volume expansion feature is GA'ed from k8 side so we will be working on including it CSI driver

**Comment by deeghuge** [comment]
Closing since feature is implemented and will be available as part of 2.4.0
