### ISSUE TITLE
Remove CSI_LOGLEVEL=trace from deamonset env var list 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#854]
## Describe the bug
Remove CSI_LOGLEVEL=trace from deamonset env var list 

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. List env var  from driver plugin deamonset

```
oc set env ds/ibm-spectrum-scale-csi --list|grep CSI_LOGLEVEL
CSI_LOGLEVEL=trace

```

## Expected behavior
Remove CSI_LOGLEVEL=trace from deamonset env var list 

CSI Build version :
```
oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.9.0     True
```

**Comment by ghanshyam-11** [comment]
A PR [](https://github.com/IBM/ibm-spectrum-scale-csi/pull/903) has been merged in dev for the above issue.

**Comment by Jainbrt** [comment]
Verified on  image : 

```
quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.9.0-170223
quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator:v2.9.0-170223
```
