### ISSUE TITLE
Remove clusterId param from storage class

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#86]
When I use storage class for dynamic provisioning fileset, I need to specify clusterId. Without it, I get this error in my PVC:
```
failed to provision volume with StorageClass "ibm-spectrum-scale-csi-remotefs-wicid": rpc error: code = InvalidArgument desc = clusterId not specified in request parameters
```

It does not make any sense to require this parameter. The filesystem names are unique in a cluster. Locally mounted remote filesystems must have unique names too. I think you should remove this parameter or make it optional in storage classes.

**Comment by deeghuge** [comment]
For primary cluster we made clusterID optional in storageClass so if it is not specified we will use the primary cluster ID.

For now it is not possible to derive clusterID for remote filesystem hence it will be required while defining storageClass for remote filesystem.

**Comment by deeghuge** [comment]
Fixed and Verified.
