### ISSUE TITLE
Can the driver detect and bubble up an error message when the GUI hasn't been logged into?

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#88]
~If we don't think this would happen in real life, then just close this issue,~ 

What I'm looking for is some error message that is bubbled up to the user to let us know some REST service is down?  I think i hit a problem where the driver doesn't come up OK because I never logged into the SCALE GUI for the first time

Is there any messages or some command that would help me realize this mistake, `describe pods` or something else that would bubble up this user error?   I  don't think I saw it in `describe pods` but maybe i missed it?

**Comment by deeghuge** [comment]
Earlier only driver pods were doing the prerequisites check and errors are logged into driver pods logs. Now we have improved operator to check the GUI connectivity before deploying the other pods and event are generated to indicate the same. @saurabhwani5 do verify on cluster and reopen if still improvement required.
