### ISSUE TITLE
Add user friendly message hinting incorrect gui user credentials

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#89]
If I specify a wrong password for the gui user the only message from the failed csi pods is:

```
Back-off restarting failed container
```

Can you add a more user friendly message with a hint to check the credentials for the gui user?

**Comment by deeghuge** [comment]
@przem123 : Please let us know if anything is needed here.

**Comment by Jainbrt** [comment]
Closing long pending issue, @przem123 if required please open the the issue with required information.
