### ISSUE TITLE
Combined the scorecard and molecule stages in TravisCI to reduce CI time

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#9]
Discussion here: https://github.com/IBM/ibm-spectrum-scale-csi/pull/6#discussion_r370146776

<img width="755" alt="image" src="https://user-images.githubusercontent.com/10049070/72993534-90793100-3dc3-11ea-9716-363e64ece51b.png">

Creating an issue to track that enhancement.

**Comment by mew2057** [comment]
I'm going to take this one, because it's a fairly  minor change.

**Comment by mew2057** [comment]
resolved in #7
