### ISSUE TITLE
module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#919]
## Describe the bug
module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead 

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

https://github.com/golang/protobuf/blob/master/README.md

```
# grep -rni "github.com/golang/protobuf"
driver/csiplugin/identityserver.go:23:  "github.com/golang/protobuf/ptypes/wrappers"
driver/csiplugin/controllerserver.go:30:        "github.com/golang/protobuf/ptypes/timestamp"
driver/go.mod:7:        github.com/golang/protobuf v1.3.2
driver/go.sum:20:github.com/golang/protobuf v1.2.0/go.mod h1:6lQm79b+lXiMfvg/cZm0SGofjICqVBUtrP5yJMmIC1U=
driver/go.sum:21:github.com/golang/protobuf v1.3.2 h1:6nsPYzhq5kReh6QImI3k5qWzO4PEbvbIW2cwSfR/6xs=
driver/go.sum:22:github.com/golang/protobuf v1.3.2/go.mod h1:6lQm79b+lXiMfvg/cZm0SGofjICqVBUtrP5yJMmIC1U=

```

## Expected behavior
module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead

**Comment by amdabhad** [comment]
The CSI spec module - `github.com/container-storage-interface/spec`  we use needs the deprecated `github.com/golang/protobuf`, so we cannot replace it with  `google.golang.org/protobuf` unless CSI spec uses this.

**Comment by deeghuge** [comment]
Closing since it will be addressed with spec change.
