### ISSUE TITLE
Logs Required for the persistent log enabled or disable and for the wrong value 

### ISSUE THREAD

**Issue by saurabhwani5** [IBM/ibm-spectrum-scale-csi#920]
## Describe the bug
When we enable or disable the persistent logging, logs are not visible in driver pod logs. If we add wrong parameter for the same it resets to the default value for current case it is disabled and we can't see the exact behaviour 

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. Install CSI 2.9.0 dev 
```
[root@saurabh-csi-master 2202]# oc get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-4dct5                          3/3     Running   0          19m
ibm-spectrum-scale-csi-attacher-5885c459cb-srt7k      1/1     Running   0          4h51m
ibm-spectrum-scale-csi-attacher-5885c459cb-wp7zz      1/1     Running   0          4h51m
ibm-spectrum-scale-csi-gcb5s                          3/3     Running   0          19m
ibm-spectrum-scale-csi-operator-7ccc4454c9-czd2q      1/1     Running   0          49m
ibm-spectrum-scale-csi-provisioner-6b69d67cff-m5sj6   1/1     Running   0          4h51m
ibm-spectrum-scale-csi-resizer-6cc9f547d-b5tf8        1/1     Running   0          4h51m
ibm-spectrum-scale-csi-snapshotter-6cf9b7d69b-t6qx9   1/1     Running   0          4h51m
[root@saurabh-csi-master 2202]# oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.9.0     True
 
 Images :        
Operator: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator:v2.9.0-220223
Driver: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.9.0-220223
```

2. Create configmap as following :
```
[root@saurabh-csi-master 2202]# cat config.yaml
kind: ConfigMap
apiVersion: v1
metadata:
 name: ibm-spectrum-scale-csi-config
 namespace: ibm-spectrum-scale-csi-driver
data:
 VAR_DRIVER_PERSISTENT_LOG: WRONGVALUE
```
3. Now check the driver pod logs 

Observation : 
There are no logs provided for persistent log enabled or disabled or set to default in case of wrong parameter is added as shown above  

## Expected behavior
Logs or other way should be there to get the logs when we change the persistent log parameter

**Comment by deeghuge** [comment]
@saurabhwani5 Operator logs the error for invalid values. Can we please reverify and confirm.

**Comment by saurabhwani5** [comment]
closing this as we are now showing logs in cso events such as 
`  Warning  ValidationWarning  14s                    CSIScaleOperator  There are few entries having wrong values map[VAR_DRIVER_PERSISTENT_LOG:WRONGVALUE] in the configmap ibm-spectrum-scale-csi-config, default values will be used`
